pillan/rook-ceph/ceph-dashboard-ingress.yaml, pillan/rook-ceph/s3/ingress.yaml, yagan/rook-ceph/ceph-dashboard-ingress.yaml
It seems that nginx-ingress 1.1.x has a breaking change in behavior and
will now ignore any ingress resource that doesn't have a class
annotation.
=> set ingress class annotation on all ingress resources

pillan/metallb/mlb-l2.yaml
This add +4 IPs to the pool. The 140.252.146.32/27 subnet is now
exhausted except for 3 IPs in the DHCP pool.
=> (pillan) extend metallb pool to 140.252.146.46-140.252.146.59

pillan/cert-manager/cert-manager.sh, pillan/ingress/ingress-nginx-helm.sh, rancher.tu/cert-manager/cert-manager.sh, rancher.tu/ingress/ingress-nginx.sh, rancher.tu/rancher/rancher.sh, rancher.tu/rancher/values.yaml
Strange issues were observed when restarting k8s in that the ingress
controller would not pass its own http health checks.  Attempting to
reinstall the same version failed to resolve the problem.  Updating to
4.2.1 fixed the issue. The root cause is unknown.
=> (tu site) chart updates related to k8s 1.23 migration

pillan/rook-ceph/cephblockpool.yaml, pillan/rook-ceph/nfs/cephfs-jhome.yaml, pillan/rook-ceph/nfs/cephfs-lsstdata.yaml, pillan/rook-ceph/nfs/cephfs-project.yaml, pillan/rook-ceph/nfs/cephfs-scratch.yaml, pillan/rook-ceph/s3/object_store.yaml, ruka/rook-ceph/cephblockpool.yaml, ruka/rook-ceph/demo/ceph-demo-pvc.yaml, yagan/rook-ceph/cephblockpool.yaml
Quotas were already manually set on pillan & yagan and the values have been copied to the ceph CRDs without modification.
=> add quotas to ceph pools on ruka/pillan/yagan

pillan/cnpg/cnpg-backup.sh, pillan/cnpg/cnpg.sh
automatic cnpg backup problems are not solved yet, but this will allow us to "manually" backup the instance with a cronjob while we resolve this issue, also lowered the debug info on the cluster because is not needed in production.
=> CloudnativePG manual cronjob for backup

ruka/cnpg/cnpg-backup.sh, ruka/cnpg/cnpg.sh
- Adds 60 Days Lifecycle on AWS S3 Storage. (vs Lifecycle on AWS which is paid)
- Adds 5Gi as Ephemeral Storage to avoid running out of space while backing data up.
- Stop logging, bump Helm Chart version to 0.15.0 (which has v1.17.1 of cnpg), disable native backup (commented)
=> CloudnativePG Manual Backup improvements

manke/rke/cluster.yml
in order to avoid problems with etcd, we will use only 7 host on role etcd/controlplane
=> (manke) manke08, manke09 & manke10 role worker only

chonchon/metallb/metallb.sh, gaw/metallb/metallb.sh, kueyen/metallb/metallb.sh, luan/metallb/metallb.sh, lukay/metallb/metallb.sh, manke/metallb/metallb.sh, pillan/metallb/metallb.sh, rancher.cp/metallb/metallb.sh, rancher.ls/metallb/metallb.sh, rancher.tu/metallb/metallb.sh, ruka/metallb/metallb.sh, yagan/metallb/metallb.sh, yepun/metallb/metallb.sh
Josh found that metallb version 0.13.7 was suddenly stop working after a few hours on the LHN link project, by updating to version 0.13.9, all clusters have been stable.
=> Metallb 0.13.9 version Bump

ruka/ingress/lhn/ingress-nginx-lhn.sh, ruka/ingress/lhn/ingress-s3-lhn.yaml
This adds a second ingress controller and add the ingress for the s3 on rook as part of the test we did to implement this into chonchon.
=> (ruka) Add LHN ingress controller for rook-ceph

yagan/cnpg/cnpg-replica-lb.yaml, yagan/cnpg/cnpg.sh
This add the replication config in the ```pg_hba``` to the user ```replicauser``` and applies a new service using the Metallb annotation to grab an IP from the pool exposed to the USDF.
=> (Yagan) Add cnpg replication to USDF

manke/cnpg/cnpg-backup.sh, pillan/cnpg/cnpg-backup.sh, ruka/cnpg/cnpg-backup.sh, yagan/cnpg/cnpg-backup.sh
cloudnativepg backups needed an update in the TTS because the amounts of files were not been erased past 60 days.
=> (pillan/manke/yagan/ruka) cnpg backup image to lsstit dockerhub

pillan/ingress/ingress-nginx.sh, pillan/metallb/demo/metallb-demo-general.yaml, pillan/metallb/ippool.yaml, pillan/rook-ceph/nfs/cephfs-auxtel.yaml, pillan/rook-ceph/nfs/cephfs-jhome.yaml, pillan/rook-ceph/nfs/cephfs-lsstdata.yaml, pillan/rook-ceph/nfs/cephfs-obsenv.yaml, pillan/rook-ceph/nfs/cephfs-project.yaml, pillan/rook-ceph/nfs/cephfs-scratch.yaml, pillan/rook-ceph/rook-ceph.sh
The current metallb pool on pillan is full and can't be expanded as the subnet is also full. A new /27 has been allocated to be the new default pool while leaving the existing pool in place.
This is not a complete solution as new routes will also be needed to make this work but can't be applied as this time due to release testing on pillan.
=> (pillan) add metallb "general" pool; add auxtel nfs export; pin nfs svc IPs

manke/rook-ceph/cephblockpool.yaml, manke/rook-ceph/rook-ceph-cluster-values.yaml
influxDB needs two deployments at base (manke) in order to restore when data is lost, so 10 Disk 1.92Tb were added and the rook-ceph deployment was adjusted to hold this two instances (5tb ea~)
=> (manke) add disks and set replicapool quota 15Ti

konkong/rook-ceph/s3/rgw-lfa.yaml, konkong/rook-ceph/s3/rgw-o11y.yaml
the ingress for the o11y access had the same name as the original lfa s3 ingress so it got overwritten... also changed the certs issuer to cluster-issuer both certs got signed correctly.
=> (konkong) fix lfa ingress for o11y s3

ruka/rke/cluster.yml
This upgrades the version of k8s on ruka to 1.25.9
=> (ruka) rke bump k8s to v1.25.9-rancher2-2

ayekan/mimir/deploy-mimir.sh, ayekan/mimir/values.yaml, ayekan/prometheus/prometheus.sh, ayekan/prometheus/values.yaml
This deploys the Mimir cluster to Ayekan and ensures that the local prometheus writes to it. It also configures the prometheus to only use serviceMonitors from `o11y.eu/monitor=enabled` namespaces.
=> (ayekan) Configure Prometheus for Mimir remote write and deploy Mimir

.gitignore, ayekan/exporters/blackbox-exporter.yaml, ayekan/exporters/deploy-exporters.sh, ayekan/exporters/snmp-configmap.tmpl, ayekan/exporters/snmp-configmap.yaml, ayekan/exporters/snmp-exporter.yaml, ayekan/prometheus/values.yaml
This should cause the blackbox exporter to start probing all the node-exporter machines.
TODO: configure some SNMP targets as well
=> (ayekan) Setup basic exporters to scrape machines

ayekan/prometheus/values.yaml
Assigns 10GB persistent storage to the Grafana instances in the helm chart.
=> (ayekan) enable grafana persistence across boots

ayekan/mimir/values.yaml
Enable the `metamonitoring` for Mimir, which implements alerting rules, dashboards and serviceMonitors for the Mimir components.
=> (ayekan) enable monitoring on Mimir

.gitignore, ayekan/prometheus/prometheus.sh, ayekan/prometheus/values.yaml
This enabled the slack connection from alertmanager, enabling alert sending to slack. Meanwhile also correctly setting the externalURL of both prometheus and alertmanager (to make the alerts functional).
Only a DNS entry for `alertmanager.ayekan.ls.lsst.org` needs to be configured (as currently the links fail).
If somebody knows a better way around `--set "alertmanager.config.receivers[1].slack_configs[0].api_url=${O11Y_SLACK_API_URL}` I'd be happy to replace the fragile bash.
=> (ayekan) enable slack/squadcast connection for alertmanager

ayekan/kyverno/kyverno.sh, ayekan/kyverno/servicemonitor.yaml
Deploy the kyverno servicemonitor into ayekan. This allows prometheus to scrape kyverno metrics.
=> (ayekan) deploy kyverno servicemonitor

ayekan/prometheus/values.yaml
Due to Rancher, some components are missing from their standard places in kubernetes and this triggers unactionable alerts from the prometheus stack.
=> (ayekan) fix prometheus alerts for missing k8s components

fleet/lib/kube-prometheus-stack/fleet.yaml
and add the `o11y.eu/monitor` label to the `kube-prometheus-stack` ns.
This will harmonize the entire fleet with the version deployed on ayekan.
=> (fleet/kube-prometheus-stack) bump kube-prometheus-stack to v56.19.0

fleet/lib/rook-ceph-conf/charts/pillan/templates/cephobjectstore-o11y.yaml
Provision a new rgw instance accessible as s3.o11y.tu.lsst.org to sort metrics and logs for the TTS.
=> (pillan) add o11y rgw

fleet/lib/fleet-conf/overlays/tu/gitrepo-pillan.yaml, fleet/lib/metallb-conf/fleet.yaml, fleet/lib/metallb-demo/fleet.yaml, fleet/lib/multus-conf/fleet.yaml, fleet/lib/multus-demo/fleet.yaml, fleet/lib/rook-ceph-cluster/fleet.yaml, fleet/lib/rook-ceph-conf/fleet.yaml, fleet/lib/rook-ceph-demo/Chart.yaml, fleet/lib/rook-ceph-demo/fleet.yaml
pillan was deleted from and re-imported into rancher.tu.lsst.org in order to fix the cluster name.
=> (pillan) fix cluster name in rancher: c-st7p2 -> pillan

rancher.cp/onepassword/values.yaml, rancher.ls/onepassword/values.yaml, rancher.tu/onepassword/values.yaml
These values.yaml files were unintentionally excluded by the root .gitignore.
=> (rancher.*) fix missing onepassword chart values

fleet/lib/fleet-conf/overlays/cp/gitrepo-chonchon.yaml, fleet/lib/fleet-conf/overlays/cp/gitrepo-lukay.yaml, fleet/lib/fleet-conf/overlays/dev/gitrepo-ayekan.yaml, fleet/lib/fleet-conf/overlays/dev/gitrepo-kueyen.yaml, fleet/lib/fleet-conf/overlays/dev/gitrepo-namkueyen.yaml, fleet/lib/fleet-conf/overlays/dev/gitrepo-ruka.yaml, fleet/lib/fleet-conf/overlays/ls/gitrepo-gaw.yaml, fleet/lib/fleet-conf/overlays/ls/gitrepo-konkong.yaml, fleet/lib/fleet-conf/overlays/ls/gitrepo-luan.yaml, fleet/lib/fleet-conf/overlays/ls/gitrepo-manke.yaml, fleet/lib/fleet-conf/overlays/tu/gitrepo-pillan.yaml
With the exception of the dev site, which will use the `master` branch. `cp_production` will be used for the `cp` site to be consistent with `lsst-it/lsst-control`.
Map of sites to github branch names:
dev: master
tu: tu_production
ls: ls_production
cp: cp_production
=> (fleet) use a github branch per site

fleet/lib/cert-manager-conf/fleet.yaml, fleet/lib/cert-manager-conf/overlays/konkong/clusterissuer-letsencrypt-dev.yaml, fleet/lib/cert-manager-conf/overlays/konkong/clusterissuer-letsencrypt-staging.yaml, fleet/lib/cert-manager-conf/overlays/konkong/clusterissuer-letsencrypt.yaml, fleet/lib/cert-manager-conf/overlays/konkong/externalsecret-route53.yaml, fleet/lib/cert-manager-conf/overlays/konkong/kustomization.yaml, fleet/lib/rook-ceph-cluster/overlays/ayekan/values.yaml
This clusterissuer is already in use on konkong but missing from the fleet configuration.
=> (konkong) add letsencrypt-dev clusterissuer

fleet/lib/kube-prometheus-stack/overlays/pillan/values.yaml, fleet/lib/kube-prometheus-stack/overlays/ruka/values.yaml
This includes select puppet enc data being used as prometheus labels.
Requires https://github.com/lsst-it/lsst-control/pull/1110
=> (fleet/kube-prometheus-stack) add puppetdb sd for node exporter

fleet/lib/cnpg-system/fleet.yaml
the release name didn't match the old helm release name
=> (pillan) fleet cnpg typo fix

fleet/lib/multus/multus-daemonset-thick.yml
This attempts to resolve the kube-mutlus-ds pods being killed by the oom.
=> (fleet/multus) increase request to 64Mi; limit to 128Mi

fleet/lib/multus-conf/overlays/yagan/net-attach-def-dds.yaml, fleet/lib/multus-conf/overlays/yagan/net-attach-def-macvlan-conf.yaml
Instead of directly using vlan interface names, which vary by node.
=> (yagan) fix net-attach-def's to use bridge interfaces

fleet/lib/cnpg-system/fleet.yaml
This is to resolve the oom killing the cnpg operator.
=> (fleet/cnpg-system) increase mem to 192Mi/384Mi

fleet/lib/cnpg-cluster/overlays/ruka/cnpg-loadBalancer.yaml, fleet/lib/cnpg-cluster/overlays/yagan/cnpg-loadBalancer-lhn.yaml, fleet/lib/cnpg-cluster/overlays/yagan/cnpg-loadBalancer.yaml, fleet/lib/cnpg-cluster/overlays/yepun/cnpg-loadBalancer.yaml
As multiple svcs with nodeport enabled with cause a port allocation conflict.
The svc's for pillan and manke were not updated as those production deployments are currently working. Those deployments should be updated when convenient.
=> (ruka,yagan,yepun) do not enable svc nodeports

fleet/lib/velero/fleet.yaml
Resolves this error seen on k8s 1.29.2:
k logs velero-upgrade-crds-6gj64
Defaulted container "velero" out of: velero, kubectl (init)
/tmp/sh: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/sh)
/tmp/sh: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/sh)
=> (fleet/velero) bump chart to 5.4.1

ayekan/rke/cluster.yml, kueyen/rke/cluster.yml, namkueyen/rke/cluster.yaml, rancher.dev/rancher/values.yaml, rancher.dev/rke/cluster.yml, ruka/rke/cluster.yml
The number of allowed pods per node is increased from the default of 110 to 250.
Depends on https://github.com/lsst-it/lsst-control/pull/1127
=> (dev/*) bump k8s to v1.27.12-rancher1-1

fleet/lib/kube-prometheus-stack/overlays/ayekan/values.yaml
Add the same http basic auth to ayekan as was introduced in #304 .
=> (ayekan) enable puppetdb http basic auth + use enc data as labels

fleet/lib/blackbox-exporter/values.yaml
The existing cert/secret name is tls-snmp-exporter-ingress which is the same as being used by our snmp-exporter deployment.  This is clearly a typo.
=> (fleet/blackbox-exporter) fix ing host & tls secret name

fleet/lib/rook-ceph-conf/charts/konkong/templates/cephobjectstore-o11y.yaml
To allow the pool to function normally as usage is reduced.
=> (konkong) increase o11y rgw quota to 1.05TiB

fleet/lib/rook-ceph-cluster/fleet.yaml
This was added to the rook-ceph-cluster default values.yaml with a value of false, which rook then deletes from the CephCluster resource.
=> (fleet/rook-ceph-cluster) ignore spec.upgradeOSDRequiresHealthyPGs

fleet/lib/rook-ceph-cluster/values.yaml
Provisioning of OSDs size sizes of at least 4TiB was broken because of the memory limit being set on the osd-prepare job(s).
See: https://github.com/rook/rook/commit/a84aeebb4d7d889368b1161bb2e556a3cb695b11
=> (fleet/rook-ceph-cluster) fix osd provisioning; set prepareosd to 32Gi

fleet/lib/kube-prometheus-stack/aggregator/values.yaml, fleet/lib/kube-prometheus-stack/fleet.yaml
The existing `site` external label would conflict with the labels being set on node-exporter metrics discovered via puppetdb, which is why it has been renamed to `prom_site`.
=> (fleet/kube-prometheus-stack) add externalLabels to all clusters

fleet/lib/mimir/values.yaml
Resolves this warning in the ingress-nginx logs:
2024/05/17 03:39:08 [warn] 5373#5373: *16612410 a client request body is buffered to a temporary file /tmp/nginx/client-body/0000145434, client: 10.42.0.0, server: mimir.ruka.dev.lsst.org, request: "POST /api/v1/push HTTP/2.0", host: "mimir.ruka.dev.lsst.org"
=> (fleet/mimir) set ingress client-body-buffer-size to 10m

fleet/lib/multus-conf/overlays/manke/net-attach-def-htcondor.yaml, fleet/lib/multus-conf/overlays/ruka/net-attach-def-htcondor.yaml, fleet/lib/multus-conf/overlays/yagan/net-attach-def-htcondor.yaml
getting the route from the current network is messing with the name resolution inside k8s network, skipping the default will force to resolve inside k8s
=> (fleet/multus) Fix htcondor to skip default route

fleet/lib/mimir/values.yaml
This change has been confirmed as working by inspecting the compactor pod logs:
ts=2024-05-13T19:03:05.618115801Z caller=blocks_cleaner.go:629 level=info component=cleaner run_id=1715626985 task=clean_up_users user=anonymous msg="marked blocks for deletion" num_blocks=0 retention=17520h0m0s
=> (fleet/mimir) set a default metric retention period of 2 years

fleet/lib/external-secrets-conf/fleet.yaml, fleet/lib/external-secrets-conf/overlays/antu/clustersecretstore-onepassword.yaml, fleet/lib/external-secrets-conf/overlays/manke/clustersecretstore-onepassword.yaml
Cluster level vaults have only been created for:
- antu
- manke
The vaults should be created for other clusters as they are needed.
=> (site/ls) refactor 1pass: <cluster> -> k8s-<site> -> k8s-common

fleet/lib/kube-prometheus-stack/aggregator/values.yaml
In order to replace it with a custom prometheusrule.
=> (fleet/kube-prometheus-stack) disable default TargetDown prometheusrule

fleet/lib/mimir/values.yaml
Mimir got a lot of log message due to out-of-order samples being send to it. This PR configures a tiny out-of-order window for the samples to be ingested.
We also tune the Mimir pod resources to be able to handle the data ingestion that's going on.
=> Tune Mimir resource allocation and out-of-order time window

fleet/lib/kube-prometheus-stack/fleet.yaml, fleet/s/ls/c/antu/kube-prometheus-stack, fleet/s/ls/c/antu/kube-prometheus-stack-pre, fleet/s/ls/c/antu/prometheus-operator-crds
This also enables shipping prom metrics from dev, ls, & cp k8s clusters to antu & ruka.
=> (antu) add kube-prometheus-stack

fleet/lib/kube-prometheus-stack/aggregator/values.yaml, fleet/lib/kube-prometheus-stack/fleet.yaml, fleet/lib/kube-prometheus-stack/values.yaml
At present, only manke is scraping ceph metrics and sending them to ayekan (it isn't clear why that is working). The intent was for all dev, cp, & ls clusters to be scraping and forwarding metrics to mimir on ayekan.
=> (fleet/kube-prometheus-stack) enable scrape labels on "client" clusters

fleet/lib/rook-ceph-conf/charts/pillan/templates/cephobjectstore-o11y.yaml
This was accidentially broken by:
https://github.com/lsst-it/k8s-cookbook/pull/416
=> (pillan) fix mimir s3 fqdn

fleet/lib/prometheus-operator-crds/fleet.yaml
To resolve this error seen when updating ancient deployments:
ErrApplied(1) [Cluster fleet-local/local: cannot patch "alertmanagers.monitoring.coreos.com" with kind CustomResourceDefinition: CustomResourceDefinition.apiextensions.k8s.io "alertmanagers.monitoring.coreos.com" is invalid: spec.preserveUnknownFields: Invalid value: true: must be false in order to use defaults in the schema && cannot patch "prometheuses.monitoring.coreos.com" with kind CustomResourceDefinition: CustomResourceDefinition.apiextensions.k8s.io "prometheuses.monitoring.coreos.com" is invalid: spec.preserveUnknownFields: Invalid value: true: must be false in order to use defaults in the schema && cannot patch "servicemonitors.monitoring.coreos.com" with kind CustomResourceDefinition: …
=> (fleet/prometheus-operator-crds) force install

fleet/lib/external-secrets-conf/fleet.yaml
The 1pass vaults for the "rancher" clusters are named `rancher.<site>` but rancher/fleet insistent on naming these clusters `local` within fleet.
=> (fleet/external-secrets-conf) fix vault name for rancher clusters

fleet/lib/kube-prometheus-stack/aggregator/values.yaml
On the ruka cluster, both the grafana-sc-dashboard and grafana-sc-datasources containers in the grafana pod have restarted because of an Error. The cause of these restarts isn't clear. E.g.
State:           Running
Started:       Mon, 13 May 2024 01:01:03 -0700
Last State:      Terminated
Reason:        Error
Exit Code:     1
Started:       Sun, 12 May 2024 23:59:38 -0700
Finished:      Mon, 13 May 2024 01:01:02 -0700
Ready:           True
Restart Count:   2
=> (fleet/kube-prometheus-stack) increase grafana sidecar limit to 512Mi

fleet/lib/mimir/values.yaml
To resolve distributor pods being OOMKilled on ruka:
mimir-distributed-distributor-7767d66476-cdh6f         0/1     OOMKilled     1 (61s ago)     2m4s
mimir-distributed-distributor-7767d66476-cgf4b         0/1     OOMKilled     1 (72s ago)     2m18s
Increasinig the limit to 8Gi was tested and pods were still getting OOMKilled.
=> (fleet/mimir) increase distributor mem to 12Gi

fleet/lib/mimir/values.yaml
This error has been observed in the ingester logs on ruka while processing WAL logs:
ts=2024-05-31T16:28:20.612605482Z caller=head.go:819 level=info user=anonymous msg="WAL segment loaded" segment=12510 maxSegment=12605
panic: preallocate: no space left on device
goroutine 606 [running]:
github.com/prometheus/prometheus/tsdb.handleChunkWriteError({0x31cb7e0, 0xc280674e40})
/__w/mimir/mimir/vendor/github.com/prometheus/prometheus/tsdb/head_append.go:1529 +0x5c
github.com/prometheus/prometheus/tsdb/chunks.(*chunkWriteQueue).processJob(0xc0009158c0, {0x1, 0x1fa37f2, 0x18fcca80617, 0x18fcccd8f77, {0x31f2a40, 0xc21a82c380}, 0x4200000008, 0x0, 0x2c32f90})
/__w/mimir/mimir/vendor/github.com/prometheus/prometheus/tsdb/chunks/chunk_write_queue.go:139 +0x82 …
=> (fleet/mimir) increase ingester pvc size to 100Gi

fleet/lib/snmp-exporter-pre/files/sd/dev/snmp-raritan-pdu.json
All records in the ls.lsst.org & cp.lsst.org zones which match /pdu/ have been scraped into this update.
=> (fleet/snmp-exporter-pre) update snmp-raritian-pdu.json from route53

.gitignore
This was useful when secrets were being inserted into helm values.yaml files but it is now generally a source of errors with fleet/helm values.yaml accidentally not being committed to the repo.
=> (.gitignore) allow values.yaml to be committed

fleet/lib/mimir/values.yaml
Mimir gateway acts as a shadow ingress for mimir components.  Lets keep the ingress resource and gateway buffer sizes in sync.
=> (fleet/mimir) set ingress & gateway set buffer sizes to 10m

fleet/lib/kube-prometheus-stack/values.yaml
RemoteWrite clients of both ruka & antu have been getting HTTP 429s.  Enabling this feature is supposed to enable the prometheus instance to retry the remoteWrite.
ts=2024-06-03T22:09:41.128Z caller=dedupe.go:112 component=remote level=error remote_name=43e475 url=https://mimir.ruka.dev.lsst.org/api/v1/push msg="non-recoverable error" count=1975 exemplarCount=0 err="server returned HTTP status 429 Too Many Requests: the request has been rejected because the tenant exceeded the ingestion rate limit, set to 500000 items/s with a maximum allowed burst of 1000000. This limit is applied on the total number of samples, exemplars and metadata received across all distributors (err-mimir-tenant-max-ingestion-rate). To adjust the related per-tenant limits, configure …
=> (fleet/kube-prometheus-stack) enable remoteWrite retry on http429

fleet/lib/mimir/values.yaml
We don't currently implement ceph availability zones and have no plans to do so.  The zoneAwareReplication functionality in the mimir chart is largely cosmetic in that it will create multiple sts, zone per configured zone, instead of a single sts with multiple instances.  However, when scaling the number of replicas of a service up or down, the full set of zones needs to be manual enumerated and it seems like the minimum number is 3 and we would like to be able to use fewer instances on dev clusters.
=> (fleet/mimir) disable zoneAwareReplication

fleet/lib/mimir/values.yaml
When running 3 ingestor instances and requiring 3 replicas any distriburance to an ingestor pod causes metrics to stop being accepted. This includes rollouts, drains, and node failure.  In order to support operators the number of replicas should always be at least 1 less than the number of ingestor instances.
Changing from 3 to 2 replicas also reduces the ammount of write amplication.
=> (fleet/mimir) change ingestor replication_factor to 2

gaw/rke/cluster.yml, konkong/rke/cluster.yml, luan/rke/cluster.yml, manke/rke/cluster.yml, rancher.ls/rke/cluster.yml
Bumping k8s clusters to 1.28.9 on LS
=> (site/ls) bump rke to v1.28.9-rancher1-1

fleet/lib/mimir/README.md
It seems that radosgw-admin commands now require the realm and zonegroup to be specified even when the name of the zone would be non-ambiguous.
=> (fleet/mimir) update README to work with ceph 18.x

fleet/lib/mimir/values.yaml
To resolve this error message seen on ruka:
ts=2024-06-05T18:21:04.930841052Z caller=bucket_compactor.go:256 level=error component=compactor user=anonymous groupKey=0@17241709254077376921-merge--1717200000000-1717286400000 minTime="2024-06-01 00:00:00 +0000 UTC" maxTime="2024-06-02 00:00:00 +0000 UTC" msg="compaction job failed" duration=15m6.473521261s duration_ms=906473 err="compact blocks 01HZAAF4WA2CA82NKYN5ZH05Z9,01HZBDNFQ2N0JA57D6TPYQSB8Q: 3 errors: preallocate: no space left on device; sync /data/compact/0@17241709254077376921-merge--1717200000000-1717286400000/01HZMSKK57DZXZP59M2T5QB4QE.tmp-for-creation/chunks/000029: file already closed; write /data/compact/0@17241709254077376921-merge--1717200000000-1717286400000/01HZMSKK57DZXZP59M2T5QB4QE.tmp-for-creation/index_tmp_p: no space …
=> (fleet/mimir) increase compactor disk size to 100Gi

fleet/lib/snmp-exporter-pre/fleet.yaml
It seems that recent release of external-secrets has changed behavior and it is now an error to have templated values in a cm template that do not have a value to interpolate.
=> (fleet/snmp-exporter-pre) enable interpolation of snmpLsstCommunity

fleet/lib/kube-prometheus-stack/fleet.yaml, fleet/lib/kube-prometheus-stack/pvc/values.yaml
On clusters which have ceph configured to provide pvcs, this will prevent the prometheus tsdb from growing unbounded in the ephemeral disk space of the node on which the sts is scheduled.
=> (fleet/kube-prometheus-stack) use a ceph backed pvc for prometheus data

fleet/lib/kube-prometheus-stack/aggregator/values.yaml, fleet/lib/kube-prometheus-stack/overlays/ayekan/values.yaml, fleet/lib/kube-prometheus-stack/values.yaml
The prometheus stack config drift has gotten a bit too large. Use this task to clean up smaller parts that do not belong into a larger task.
Part of splitting https://github.com/lsst-it/k8s-cookbook/pull/346 into smaller chunks.
=> (fleet/prom-stack) Prometheus stack config cleanup

fleet/lib/kube-prometheus-stack-pre/externalsecret-grafana-opensearch.yaml, fleet/lib/kube-prometheus-stack/aggregator/values.yaml
Splitting up https://github.com/lsst-it/k8s-cookbook/pull/346
This PR splits out the data source addition from https://github.com/lsst-it/k8s-cookbook/pull/346/commits into a smaller commit, making the merge easier on both sides.
=> (fleet/grafana) Add opensearch logging datasource to aggregator Grafana

rancher.cp/onepassword/.gitignore, rancher.cp/onepassword/fetch-credentials.sh, rancher.dev/onepassword/.gitignore, rancher.dev/onepassword/fetch-credentials.sh, rancher.ls/onepassword/.gitignore, rancher.ls/onepassword/fetch-credentials.sh, rancher.tu/onepassword/.gitignore, rancher.tu/onepassword/fetch-credentials.sh, template/onepassword/README.md, template/onepassword/onepassword-connect.sh
Fleet will install / upgrade the onepassword-connect chart going forward.  As the credentials are being installed "manually", they will not be owned by the currently installed chart release and will not be uninstalled when the chart release is upgraded by fleet.
=> (rancher.*) convert onepassword-connect install to be credentials only

fleet/lib/prometheus-alerts/Chart.yaml, fleet/lib/prometheus-alerts/README.md, fleet/lib/prometheus-alerts/fleet.yaml, fleet/lib/prometheus-alerts/templates/prometheusrule.yaml, fleet/lib/prometheus-alerts/values.yaml
This allows for prometheus rules to be automagically applied through rancher fleet. Simply adding some rules to the fleet directory will deploy them into the cluster, ready for the prometheus operator to pick them up and deploy.
Split out of #346 with minor modifications.
=> (fleet/prometheus-alerts) set up gitops for alert deployment

fleet/lib/blackbox-exporter/fleet.yaml, fleet/lib/cert-manager-conf/fleet.yaml, fleet/lib/cnpg-cluster/fleet.yaml, fleet/lib/fluentbit/fleet.yaml, fleet/lib/ingress-nginx-lhn/fleet.yaml, fleet/lib/ingress-nginx/fleet.yaml, fleet/lib/kube-prometheus-stack-pre/fleet.yaml, fleet/lib/metallb-demo/fleet.yaml, fleet/lib/mimir-pre/fleet.yaml, fleet/lib/multus-demo/fleet.yaml, fleet/lib/opensearch-logging/fleet.yaml, fleet/lib/rook-ceph-cluster/fleet.yaml, fleet/lib/rook-ceph-conf/fleet.yaml, fleet/lib/rook-ceph-demo/fleet.yaml, fleet/lib/snmp-exporter-pre/fleet.yaml, fleet/lib/snmp-exporter/fleet.yaml, fleet/lib/velero-conf/fleet.yaml
Reducing the complexity of the dep graph will speed up convergence time.
=> (fleet/*) prune unnecessary bundle deps

fleet/lib/ccs-grafana/base/externalsecret-grafana.yaml, fleet/lib/ccs-grafana/base/kustomization.yaml, fleet/lib/ccs-grafana/fleet.yaml, fleet/lib/ccs-grafana/values.yaml, fleet/lib/ccs-influxdb/base/externalsecret-influxdb.yaml, fleet/lib/ccs-influxdb/base/kustomization.yaml, fleet/lib/ccs-influxdb/fleet.yaml, fleet/lib/ccs-influxdb/values.yaml, fleet/s/dev/c/kueyen/ccs-grafana, fleet/s/dev/c/kueyen/ccs-influxdb
This adds an infludb and grafana instance to `kueyen`, soon `manke` and `yepun` will follow this.
=> (ccs-influxdb/grafana) into fleet dev/kueyen

fleet/lib/prometheus-alerts/rules/prometheusrule-net.yaml
The `---` yaml header was breaking the helm templating of the `prometheusrule` CR.
=> (fleet/prometheus-alerts) fix HostDown rule

fleet/lib/kube-prometheus-stack/pvc/values.yaml
On antu, a 50GiB PVC was not large enough for prom default 15 day retention period.  To prevent this from happening we are enlarging the PVC so that it should accommodate ~1weeks worth of data even on an aggegration cluster and switch from time to a size based retention window.
=> (fleet/kube-prometheus-stack) fix prom pvc filling up

fleet/lib/kube-prometheus-stack/fleet.yaml
As konkong does not have ceph rbd deployed.
=> (fleet/kube-prometheus-stack) disable prom pvc on konkong

fleet/lib/kube-prometheus-stack/fleet.yaml
As chonchon does not have ceph rbd deployed.
=> (fleet/kube-prometheus-stack) disable prom pvc on chonchon

fleet/lib/kube-prometheus-stack/values.yaml
On yagan, the kube-state-metrics pod is beeing OOMKilled.
=> (fleet/kube-prometheus-stack) set kube-state-metrics limit to 384Mi

fleet/lib/cnpg-cluster/overlays/yagan/cluster-cnpg-cluster.yaml
cnpg resources were a bit tight on the summit.
current: 750m~ CPU / 914 MEM
=> (fleet/cnpg-cluster) more resource to yagan deploy

chonchon/rke/cluster.yml, lukay/rke/cluster.yml, rancher.cp/rke/cluster.yml, yagan/rke/cluster.yml, yepun/rke/cluster.yml
bumping k8s version to 1.28.10 on all CP clusters.
=> (site/cp) bump rke to v1.28.10-rancher1-1

fleet/lib/local-static-provisioner/fleet.yaml, fleet/lib/local-static-provisioner/values.yaml, fleet/s/dev/c/kueyen/local-static-provisioner, kueyen/rke/cluster.yml
when using a container version of kubelet, we need to add that bind to get  permissions to access that path.
the labels are for nodeSelector.
=> (fleet/local-static-provisioner) add deployment on kueyen

fleet/s/ls/c/manke/local-static-provisioner, manke/rke/cluster.yml
need to add the local provisioner to Manke to mount Kafka there on Manke08, 09, and 10.
=> (fleet/local-static-provisioner) add deployment on manke

fleet/lib/mimir/values.yaml
This commit adds a gateway.nginx.config.clientMaxBodySize value which replaces the need for setting the client_max_body_size nginx parameter via a custom config snippet:
https://github.com/grafana/mimir/commit/ef00f588e837ec9c28c740afebecaafba5f9d1e1
=> (fleet/mimir) set gw client_max_body_size via new chart value

yagan/rke/cluster.yml
we added a disk to yagan17 to hold the influxDB deployment on a separate node.
=> (fleet/local-static-provisioner) add label on yagan17

fleet/lib/rook-ceph-conf/charts/pillan/templates/cephnfs-rsphome.yaml, fleet/lib/rook-ceph-conf/charts/pillan/templates/cm-cephcli.yaml, fleet/lib/rook-ceph-demo/fleet.yaml
forgot to merge the rsphome before so now it is been added to the fleet deployment
=> (fleet/rook-ceph-conf) add rsphome export to pillan

fleet/lib/kyverno/fleet.yaml
Revert https://github.com/lsst-it/k8s-cookbook/pull/544 as it broke the `kyverno-reports-controller`. E.g.:
```
$ k logs kyverno-reports-controller-9d8b78cd4-45t5p
flag provided but not defined: -maxAdmissionReports
Usage of /ko-app/reports-controller:
-add_dir_header
If true, adds the file directory to the header of the log messages
-admissionReports
...
```
=> Revert "Merge pull request #544 from lsst-it/renovate/kyverno-3.x"

fleet/lib/rook-ceph-conf/charts/yagan/templates/cephnfs-auxtel.yaml
we saw the OOM Killer do his thing on the `nfs-auxtel-a` pod causing it to restart.
=> (fleet/rook) set limits on auxtel mds to 16Gi on Yagan

fleet/lib/cnpg-cluster/overlays/yagan/cluster-cnpg-cluster.yaml
Butler database on `cloudnativePG` on `Yagan` filled the PVC, so it was increased from `5Gi` to `10Gi`
=> (fleet/cnpg-cluster) PVC bump to 10Gi on yagan

fleet/lib/alertbit/fleet.yaml, fleet/lib/alertmanager2kafka/fleet.yaml, fleet/lib/cert-manager-conf/fleet.yaml, fleet/lib/cert-manager-crds/fleet.yaml, fleet/lib/cnpg-cluster/fleet.yaml, fleet/lib/cnpg-system/fleet.yaml, fleet/lib/external-secrets-conf/fleet.yaml, fleet/lib/fleet-conf/fleet.yaml, fleet/lib/fluentbit/fleet.yaml, fleet/lib/htcondor/fleet.yaml, fleet/lib/ingress-nginx-lhn/fleet.yaml, fleet/lib/ingress-nginx/fleet.yaml, fleet/lib/keycloak-pg/fleet.yaml, fleet/lib/keycloak-pre/fleet.yaml, fleet/lib/keycloak/fleet.yaml, fleet/lib/kyverno-conf/fleet.yaml, fleet/lib/metallb-conf/fleet.yaml, fleet/lib/multus-conf/fleet.yaml, fleet/lib/multus-demo/fleet.yaml, fleet/lib/nexus/fleet.yaml, fleet/lib/onepassword-connect/fleet.yaml, fleet/lib/opensearch-logging/fleet.yaml, fleet/lib/opensearch-operator/fleet.yaml, fleet/lib/prometheus-alerts/fleet.yaml, fleet/lib/prometheus-operator-crds/fleet.yaml, fleet/lib/rook-ceph/fleet.yaml, fleet/lib/strimzi-kafka-dashboards/fleet.yaml, fleet/lib/velero-conf/fleet.yaml
It appears (???) that setting `helm.timeoutSeconds` may help resolve the "deadlocking" that has been observed where fleet never retries a bundle deployment.
=> (fleet/*) set helm.timeoutSeconds for all bundles

fleet/lib/htcondor/overlays/yagan/deployment-htcondor-worker.yaml
on `IT-5692` it was decided to move the NFS from `comcam-archiver.cp` into the `nfs3.cp` this broke somethings including `HTCondor`
this PR goes great with https://github.com/lsst-it/lsst-control/pull/1485
=> (yagan/htcondor) fix comcam-archiver NFS to nfs3.cp

fleet/lib/rook-ceph-cluster/values.yaml
The mgr pod dashboard port now (properly) has tls disabled.
=> (fleet/rook-ceph-cluster) fix ceph dashboard ingress

fleet/lib/external-secrets-conf/fleet.yaml, fleet/lib/external-secrets-conf/templates/clustersecretstore-onepassword.yaml, fleet/lib/rook-ceph-conf/charts/chonchon/templates/cephobjectstoreuser-butler.yaml, fleet/lib/rook-ceph-conf/charts/chonchon/templates/cephobjectstoreuser-latiss.yaml, fleet/lib/rook-ceph-conf/charts/chonchon/templates/cephobjectstoreuser-lsstcam.yaml, fleet/lib/rook-ceph-conf/charts/chonchon/templates/cephobjectstoreuser-oods-latiss.yaml, fleet/lib/rook-ceph-conf/charts/chonchon/templates/cephobjectstoreuser-oods-lsstcam.yaml, fleet/lib/rook-ceph-conf/charts/elqui/templates/cephobjectstoreuser-butler.yaml, fleet/lib/rook-ceph-conf/charts/elqui/templates/cephobjectstoreuser-latiss.yaml, fleet/lib/rook-ceph-conf/charts/elqui/templates/cephobjectstoreuser-lsstcam.yaml, fleet/lib/rook-ceph-conf/charts/elqui/templates/cephobjectstoreuser-oods-latiss.yaml, fleet/lib/rook-ceph-conf/charts/elqui/templates/cephobjectstoreuser-oods-lsstcam.yaml, fleet/lib/rook-ceph-conf/charts/konkong/templates/cephobjectstoreuser-butler.yaml, fleet/lib/rook-ceph-conf/charts/konkong/templates/cephobjectstoreuser-latiss.yaml, fleet/lib/rook-ceph-conf/charts/konkong/templates/cephobjectstoreuser-lsstcam.yaml, fleet/lib/rook-ceph-conf/charts/konkong/templates/cephobjectstoreuser-oods-latiss.yaml, fleet/lib/rook-ceph-conf/charts/konkong/templates/cephobjectstoreuser-oods-lsstcam.yaml, fleet/lib/rook-ceph-conf/charts/pillan/templates/cephobjectstoreuser-butler.yaml, fleet/lib/rook-ceph-conf/charts/pillan/templates/cephobjectstoreuser-comcam.yaml, fleet/lib/rook-ceph-conf/charts/pillan/templates/cephobjectstoreuser-latiss.yaml, fleet/lib/rook-ceph-conf/charts/pillan/templates/cephobjectstoreuser-oods-comcam.yaml, fleet/lib/rook-ceph-conf/charts/pillan/templates/cephobjectstoreuser-oods-latiss.yaml, fleet/lib/rook-ceph-conf/charts/ruka/templates/cephobjectstoreuser-butler.yaml, fleet/lib/rook-ceph-conf/charts/ruka/templates/cephobjectstoreuser-latiss.yaml, fleet/lib/rook-ceph-conf/charts/ruka/templates/cephobjectstoreuser-lsstcam.yaml, fleet/lib/rook-ceph-conf/charts/ruka/templates/cephobjectstoreuser-oods-latiss.yaml, fleet/lib/rook-ceph-conf/charts/ruka/templates/cephobjectstoreuser-oods-lsstcam.yaml
The following 1pass vaults have been created to support the push of the rgw user credentials:
- oods.dev
- oods.tu
- oods.ls
- oods.cp
- oods.elqui (temporary)
=> ({chonchon,elqui,konkong,pillan,ruka}) add lfa users for oods

konkong/rook-ceph/s3/README.md, konkong/rook-ceph/s3/users-rubinobs-butler-latiss-policy.json, konkong/rook-ceph/s3/users-rubinobs-butler-lsstcam-policy.json, konkong/rook-ceph/s3/users-rubinobs-raw-latiss-policy.json, konkong/rook-ceph/s3/users-rubinobs-raw-lsstcam-policy.json
this are the policies and the instructions on how to execute ticket `IT-5301`
this most probably is going to be asked to be replicated, so don't forget about this commits.
=> (rook-ceph/konkong) add s3 policy for s3-butler and README.md

fleet/lib/rook-ceph-cluster/values.yaml
due to the lost of `pillan06`, resources need to be controlled, setting overlays is the recommended option due to different clusters and requirements. but in overall on main clusters, resources for `monitor pods` and `osd` look way high compared to `request` and `limit` configuration.
see [values.yaml](https://github.com/lsst-it/k8s-cookbook/blob/427c280bdaa1c09e2fb1529d42fb1ea24287de70/fleet/lib/rook-ceph-cluster/values.yaml#L110)
this PR is based on this pull from clusters
```
Cluster: ruka
CPU use on rook-ceph 'osd' o 'mon':
rook-ceph-osd-2-7d77c58d4b-46wkd 69m
rook-ceph-osd-3-5ddc76b-jkcvc 67m
rook-ceph-osd-4-56ddd6576f-nmqx5 61m
rook-ceph-mon-d-5bdc567795-7dm5d 56m
rook-ceph-mon-a-647bc5549-7qb8v 46m
rook-ceph-osd-0-6cf76787dd-r5btz 32m
-----------------------------------
Cluster: …
```
=> (fleet/rook-ceph-cluster) Lower CPU request osd/mon

chonchon/rke/cluster.yml, lukay/rke/cluster.yml, rancher.cp/rke/cluster.yml, yagan/rke/cluster.yml, yepun/rke/cluster.yml
this will move k8s version on cp clusters to v1.29.8 so close the October loop.
this goes great with PR https://github.com/lsst-it/lsst-control/pull/1501
=> (site/cp) bump rke to v1.29.8-rancher1-1

fleet/lib/htcondor/overlays/yagan/deployment-htcondor-worker.yaml
1st try - I tried to mount the `comcam` and `auxtel` NFS using the same `volumes`, but changing the `volumeMounts` Paths, but that didnt work...
2nd try - I tried to specify new volumes with more explicit path into the target folder, but got permission issues.
3rd try - success... i pulled an `initContainer`, created a `emptyDir`, mounted all, created the symlink and let it die in peace while the main container has the same `emptyDir` attached.
=> (yagan/htcondor) add initContainer to do symlinks

fleet/lib/ingress-nginx-lhn/fleet.yaml, fleet/lib/ingress-nginx/fleet.yaml
Migrating from ingress class annotations to the `ing.spec.ingressClassName` field caused the multiple ingress controllers to start fighting over ing resources due to misconfiguration.
=> (fleet/ingress-nginx) fix ingressClassName support

fleet/lib/rook-ceph-cluster/values.yaml
Ceph, by default, does not allow http basic auth to be set in the kafka URI unless rgw TLS is enabled.  As we terminate TLS with the ingress controller, and the communication between the ingress controller and rgw is HTTP(no-s), we need to disable this sanity check.
=> (fleet/rook-ceph-cluster) allow ceph topic configuration without TLS

fleet/lib/rook-ceph-conf/charts/chonchon/templates/cephnfs-obs-env.yaml, fleet/lib/rook-ceph-conf/charts/gaw/templates/cephnfs-backup.yaml, fleet/lib/rook-ceph-conf/charts/kueyen/templates/cephnfs-auxtel.yaml, fleet/lib/rook-ceph-conf/charts/lukay/templates/cephnfs-backup.yaml, fleet/lib/rook-ceph-conf/charts/manke/templates/cephnfs-auxtel.yaml, fleet/lib/rook-ceph-conf/charts/manke/templates/cephnfs-comcam.yaml, fleet/lib/rook-ceph-conf/charts/manke/templates/cephnfs-jhome.yaml, fleet/lib/rook-ceph-conf/charts/manke/templates/cephnfs-lsstdata.yaml, fleet/lib/rook-ceph-conf/charts/manke/templates/cephnfs-obsenv.yaml, fleet/lib/rook-ceph-conf/charts/manke/templates/cephnfs-project.yaml, fleet/lib/rook-ceph-conf/charts/manke/templates/cephnfs-scratch.yaml, fleet/lib/rook-ceph-conf/charts/namkueyen/templates/cephnfs-auxtel.yaml, fleet/lib/rook-ceph-conf/charts/pillan/templates/cephnfs-auxtel.yaml, fleet/lib/rook-ceph-conf/charts/pillan/templates/cephnfs-comcam.yaml, fleet/lib/rook-ceph-conf/charts/pillan/templates/cephnfs-jhome.yaml, fleet/lib/rook-ceph-conf/charts/pillan/templates/cephnfs-lsstdata.yaml, fleet/lib/rook-ceph-conf/charts/pillan/templates/cephnfs-obs-env.yaml, fleet/lib/rook-ceph-conf/charts/pillan/templates/cephnfs-project.yaml, fleet/lib/rook-ceph-conf/charts/pillan/templates/cephnfs-rsphome.yaml, fleet/lib/rook-ceph-conf/charts/pillan/templates/cephnfs-scratch.yaml, fleet/lib/rook-ceph-conf/charts/ruka/templates/cephnfs-auxtel.yaml, fleet/lib/rook-ceph-conf/charts/yagan/templates/cephnfs-auxtel.yaml, fleet/lib/rook-ceph-conf/charts/yagan/templates/cephnfs-comcam.yaml
This field is deprecated and has no effect.
```
~ $ k explain cephnfs.spec.rados.namespace
GROUP:      ceph.rook.io
KIND:       CephNFS
VERSION:    v1
FIELD: namespace <string>
DESCRIPTION:
The namespace inside the Ceph pool (set by 'pool') where shared NFS-Ganesha
config is stored.
This setting is deprecated as it is internally set to the name of the
CephNFS.
```
=> (fleet/rook-ceph-conf) rm usage of cephnfs.spec.rados.namespace

fleet/lib/multus-conf/overlays/kueyen/net-attach-def-ra-lhn.yaml, fleet/lib/multus-conf/overlays/yagan/net-attach-def-ra-lhn-demo.yaml, fleet/lib/multus-conf/overlays/yagan/net-attach-def-ra-lhn.yaml, fleet/lib/multus-demo/fleet.yaml
static configuration for 1 IP address that the Rapid Analysis will use to reach the USDF (tested on Kueyen working)
still need to add the CNI Plugin...
=> (fleet/multus) add configuration for ra-lhn on kueyen and yagan with demos

fleet/lib/rook-ceph-conf/charts/ruka/templates/cephobjectstoreuser-loki.yaml
This pushsecret is referencing a clustersecretstore which does not exist. Nor does this secret need to be pushed to 1pass.
Resolves this fleet error:
NotReady(1) [Bundle ruka-fleet-s-dev-c-ruka-rook-ceph-conf]; pushsecret.external-secrets.io rook-ceph/rook-ceph-object-user-lfa-loki [progressing] could not get ClusterSecretStore "onepassword-ruka.dev", ClusterSecretStore.external-secrets.io "onepassword-ruka.dev" not found
=> (ruka) rm rook-ceph/rook-ceph-object-user-lfa-loki pushsecret

chonchon/rook-ceph/s3/README.md, chonchon/rook-ceph/s3/lfa-cp-lifecycle.json
this was authorized and re-asked in the CAP Meeting on Nov 19th... according to KT, the LFA replication at the USDF only gets 1 day behind at worst scenario, so 30 days is good for the replication.
this is the last LFA without LifeCycle.
=> (lfa/policies) add Lifecycle 30 days to LFA in the Summit

fleet/lib/multus/multus-daemonset-thick.yml
Multus is tight on memory and has some restarts on Yagan... (20~ restarts, 75% used Memory)
=> (fleet/multus) raise request/limits on pod

fleet/lib/rook-ceph-conf/charts/konkong/templates/cephobjectstore-o11y.yaml
the `olly` pool was full again, we are still using it to monitor `kafka stuffs`
=> (fleet/rook-ceph-conf) buff quota for olly on konkong

konkong/rook-ceph/s3/README.md, konkong/rook-ceph/s3/rubinobs-butler-lifecycle.json
all the rubinobs buckets (EXCEPT the calibration bucket) inside the s3-butler need a 90 days safety lifecycle (the butler has a 30 days auto cleaning but this is to be sure the storage doesn't get full).
=> (konkong/s3-butler) add Lifecycle 90 days to buckets

fleet/lib/blackbox-exporter/values.yaml
add http targets to scrape ssl and response time data
=> (observability) add targets to blackbox exporter

ayekan/rke/cluster.yml, kueyen/rke/cluster.yml, namkueyen/rke/cluster.yaml, rancher.dev/rke/cluster.yml
this moves version of k8s to `v1.30.7` on those `DEV` cluster that use `RKE1`
=> (site/dev) bump rke to v1.30.7-rancher1-1

rancher.tu/rke/cluster.yml
bump `RKE1 k8s` on `rancher.dev` to `v1.30.7`
=> (site/tu) bump rke v1.6.5 for k8s v1.30.7-rancher1-1

fleet/lib/rook-ceph-conf/charts/konkong/templates/cephobjectstoreuser-calib.yaml, konkong/rook-ceph/s3/README.md, konkong/rook-ceph/s3/users-rubinobs-calibrations-policy.json
Calibrations need to go inside their own bucket with his own user. (`calib`)
quota needs to be set at `4TB`
users:
- `butler`
- `oods-lsstcam`
- `oods-latiss`
need READ Permissions. (policy done)
README.md updated
=> (rook-ceph/konkong) add calib user/bucket/quota/policies

.gitignore, fleet/lib/metallb-conf/overlays/kueyen/ipaddresspool-default.yaml
Add the IP 139.229.134.90 to metallb.
Add two files to gitignore.
=> (site/dev) Add ip to metallb on Kueyen for fluentbit external

fleet/lib/rook-ceph-conf/charts/elqui/templates/cephobjectstoreuser-comcam.yaml, fleet/lib/rook-ceph-conf/charts/elqui/templates/cephobjectstoreuser-latiss.yaml, fleet/lib/rook-ceph-conf/charts/elqui/templates/cephobjectstoreuser-lsstcam.yaml
users `comcam`, `latiss` and `lsstcam` need to own their respective `raw` and `butler` buckets, so `maxBuckets` needs to be set to `2`. (all other users are managed by policies.)
=> (elqui/rook-ceph-conf) set maxBuckets 2 users

fleet/lib/kube-prometheus-stack/overlays/antu/values.yaml
we fixed some dashboards and got duplicates... and by setting this to false, we avoid `Grafana` deploying default dashboards.
=> (fleet/kube-prometheus-stack) Set defaultDashboardsEnabled False on Antu

fleet/lib/blackbox-exporter/values.yaml, fleet/lib/kube-prometheus-stack/aggregator/values.yaml, fleet/lib/mimir/values.yaml, fleet/lib/snmp-exporter/values.yaml
This annotation was being used to disable TLS cert validation but is unnecessary when the backend is explicitly HTTP.
=> (fleet/*) rm usage of nginx.ingress.kubernetes.io/server-snippet

fleet/lib/rook-ceph-conf/charts/konkong/templates/cephnfs-auxtel.yaml, fleet/lib/rook-ceph-conf/charts/konkong/templates/cephnfs-comcam.yaml, fleet/lib/rook-ceph-conf/charts/konkong/templates/cephnfs-lsstdata.yaml, fleet/lib/rook-ceph-conf/charts/konkong/templates/cephnfs-obsenv.yaml, fleet/lib/rook-ceph-conf/charts/konkong/templates/cephnfs-project.yaml, fleet/lib/rook-ceph-conf/charts/konkong/templates/cephnfs-rsphome.yaml, fleet/lib/rook-ceph-conf/charts/konkong/templates/cephnfs-scratch.yaml, fleet/lib/rook-ceph-conf/charts/konkong/templates/cephobjectstore-lfa.yaml
To resolve this warning:
cluster:
id:     8fe980aa-b780-4e3c-b000-e07cbfcf13df
health: HEALTH_WARN
too many PGs per OSD (390 > max 250)
=> (kongkong) reduce ceph pool pg allocations by ~1/2

fleet/lib/rook-ceph-cluster/values.yaml
Disables this warning:
cluster:
id:     c3beb1c0-f8c2-4e36-8131-f53f1afdd3ed
health: HEALTH_WARN
1 pools have many more objects per pg than average
=> (fleet/rook-ceph-cluster) set mon_pg_warn_max_object_skew to "0"

fleet/lib/rancher-backup-crd/fleet.yaml, fleet/lib/rancher-backup/README.md, fleet/lib/rancher-backup/base/backup-s3-recurring.yaml, fleet/lib/rancher-backup/base/externalsecret-rancher-bkp.yaml, fleet/lib/rancher-backup/base/kustomization.yaml, fleet/lib/rancher-backup/fleet.yaml, fleet/lib/rancher-backup/values.yaml, fleet/s/cp/c/rancher/rancher-backup, fleet/s/cp/c/rancher/rancher-backup-crd, fleet/s/dev/c/rancher/rancher-backup, fleet/s/dev/c/rancher/rancher-backup-crd, fleet/s/ls/c/rancher/rancher-backup, fleet/s/ls/c/rancher/rancher-backup-crd, fleet/s/tu/c/rancher/rancher-backup, fleet/s/tu/c/rancher/rancher-backup-crd
- new Fleet Bundle installs the Rancher Backup Operator into the Rancher Clusters.
=> (fleet/rancher-backup) add rancher-backup operator on DEV

fleet/lib/cnpg-cluster/overlays/manke/cluster-cnpg-cluster.yaml, fleet/lib/cnpg-cluster/overlays/pillan/cluster-cnpg-cluster.yaml, fleet/lib/cnpg-cluster/overlays/ruka/cluster-cnpg-cluster.yaml, fleet/lib/cnpg-cluster/overlays/yagan/cluster-cnpg-cluster.yaml
-  `shared_buffers: 4GB` recommended 25% of the total RAM (more buffer, less disk writing!)
-  `work_mem: 64MB` bumping from 4MB (more memory to do `JOIN`, `SORT`, etc.)
-  `effective_cache_size: 12GB` (tells the planner it has more memory to assign ~75% of total)
-  `idle_session_timeout: 1h` (reducing the timeout for idle because of poor usage of sockets on Code connecting to DB)
=> (fleet/cnpg-cluster) boost yagan resources and buffers.

fleet/lib/cnpg-cluster/overlays/yagan/cluster-cnpg-cluster.yaml
replication es getting way behind (almost a day according to grafana) so we need more replication slots.
counting for 3 replicas:
- 3 Wal Senders.
- 3 Autovaccum
- 20 logical replication
- ~6 buffer (2 ea)
Total: 32... so i bumped `max_worker_processes: "40"` from `32`
also, from testing last night, `16Gi` of memory was on the edge around `93%` use, so bump to `32Gi` should put us on `~50%`
=> (fleet/cnpg-cluster) add more slots and memory to yagan.

fleet/lib/cnpg-cluster/fleet.yaml, fleet/lib/cnpg-cluster/overlays/manke/pooler-cnpg-cluster-pooler.yaml, fleet/lib/cnpg-cluster/overlays/pillan/pooler-cnpg-cluster-pooler.yaml, fleet/lib/cnpg-cluster/overlays/ruka/pooler-cnpg-cluster-pooler.yaml, fleet/lib/cnpg-cluster/overlays/yagan/pooler-cnpg-cluster-pooler.yaml
This will deploy the pooler in front of the database with another svc, so when ready i just need to update the DNS record to make it work.
140 x 3 pods + (special slots) vs max_connection "500"
=> (fleet/cnpg-cluster) add pgbouncer to cnpg

fleet/lib/cnpg-cluster/overlays/manke/pooler-cnpg-cluster-pooler.yaml, fleet/lib/cnpg-cluster/overlays/pillan/pooler-cnpg-cluster-pooler.yaml, fleet/lib/cnpg-cluster/overlays/ruka/pooler-cnpg-cluster-pooler.yaml, fleet/lib/cnpg-cluster/overlays/yagan/pooler-cnpg-cluster-pooler.yaml
- pgbouncer on cnpg doesnt allow settings for individual databases, so config was changed to affect all databases.
- removed the timeouts, only left the 1 hour (same as the database)
=> (fleet/cnpg-cluster) fix config pooler

antu/rke/cluster.yml, rancher.ls/rke/cluster.yml
April 2025 OS upgrades include the following:
RKE Client is bumped to v1.7.6 to support K8S version v1.31.7-rancher-1-1
This version bump will be effective as of tomorrow.
=> (site/ls) bump rke to v1.31.7-rancher1-1

fleet/lib/cnpg-cluster/overlays/manke/cluster-cnpg-cluster.yaml
- this matches `manke` and `yagan` on config.
=> (fleet/cnpg-cluster) bump manke to match yagan

fleet/lib/cnpg-cluster/overlays/manke/cluster-cnpg-cluster.yaml
- 64Gi was too much for Manke, even tho, most of the memory is just "reserved"
=> (fleet/cnpg-cluster) reduce manke memory to 32Gi

fleet/lib/ccs-influxdb/values.yaml
This solves the issue of the PVC being filled, but it is a temporary solution. Max Turri will need to find the process that is filling the PVC (as seen on the Grafana Screenshot).
=> (fleet/lib/ccs-influxdb/values.yaml) bump PVC size

fleet/lib/fleet-conf/overlays/dev/gitrepo-ayekan.yaml, fleet/lib/rook-ceph-cluster/overlays/ayekan/values.yaml, fleet/lib/rook-ceph-conf/charts/ayekan/templates/cephbuckettopic-lsst.s3.raw.comcam.yaml, fleet/lib/rook-ceph-conf/charts/ayekan/templates/cephbuckettopic-lsst.s3.raw.latiss.yaml, fleet/lib/rook-ceph-conf/charts/ayekan/templates/cephbuckettopic-lsst.s3.raw.lsstcam.yaml, fleet/lib/rook-ceph-conf/charts/ayekan/templates/cephobjectstore-lfa.yaml, fleet/lib/rook-ceph-conf/charts/ayekan/templates/cephobjectstoreuser-butler.yaml, fleet/lib/rook-ceph-conf/charts/ayekan/templates/cephobjectstoreuser-calib.yaml, fleet/lib/rook-ceph-conf/charts/ayekan/templates/cephobjectstoreuser-comcam.yaml, fleet/lib/rook-ceph-conf/charts/ayekan/templates/cephobjectstoreuser-extended-ceph-exporter.yaml, fleet/lib/rook-ceph-conf/charts/ayekan/templates/cephobjectstoreuser-latiss.yaml, fleet/lib/rook-ceph-conf/charts/ayekan/templates/cephobjectstoreuser-lsstcam.yaml, fleet/lib/rook-ceph-conf/charts/ayekan/templates/cephobjectstoreuser-oods-comcam.yaml, fleet/lib/rook-ceph-conf/charts/ayekan/templates/cephobjectstoreuser-oods-latiss.yaml, fleet/lib/rook-ceph-conf/charts/ayekan/templates/cephobjectstoreuser-oods-lsstcam.yaml, fleet/lib/rook-ceph-conf/charts/ayekan/templates/cephobjectstoreuser-rubintv.yaml, fleet/lib/rook-ceph-conf/charts/ayekan/templates/cephobjectstoreuser-s3lhn.yaml, fleet/lib/rook-ceph-conf/charts/ayekan/templates/cephobjectstoreuser-saluser.yaml, fleet/lib/rook-ceph-conf/charts/ayekan/templates/externalsecrets-kafka-bucket-notifications.yaml, fleet/lib/rook-ceph-conf/charts/ayekan/templates/obc-rubinobs-butler-comcam.yaml, fleet/lib/rook-ceph-conf/charts/ayekan/templates/obc-rubinobs-butler-latiss.yaml, fleet/lib/rook-ceph-conf/charts/ayekan/templates/obc-rubinobs-butler-lsstcam.yaml, fleet/lib/rook-ceph-conf/charts/ayekan/templates/obc-rubinobs-calibrations.yaml, fleet/lib/rook-ceph-conf/charts/ayekan/templates/obc-rubinobs-raw-comcam.yaml, fleet/lib/rook-ceph-conf/charts/ayekan/templates/obc-rubinobs-raw-latiss.yaml, fleet/lib/rook-ceph-conf/charts/ayekan/templates/obc-rubinobs-raw-lsstcam.yaml, fleet/lib/rook-ceph-conf/charts/ayekan/templates/obc-rubintv.yaml
These changesets were split out of https://github.com/lsst-it/k8s-cookbook/pull/869, which should stay on hold until Rook 1.17.2 is released, which will include the important fix https://github.com/rook/rook/pull/15816.
As other Rook configuration dev work requires a object store on ayekan, it makes sense to merge this now.
=> (ayekan) add lfa cephobjectstore w/ kafka auth from secrets

fleet/lib/kube-prometheus-stack/fleet.yaml, fleet/lib/kube-prometheus-stack/low-resource/values.yaml
- this lowers the request/limits on kube-prometheus-stack for the rancher clusters.
*this cannot go without merging first* https://github.com/lsst-it/k8s-cookbook/pull/912
=> (fleet/kube-prometheus-stack) lower request/limits on rancher clusters

fleet/lib/cnpg-cluster/overlays/yagan/cnpg-backup.yaml
To resolve this error:
+ pg_dumpall -w -U postgres -h cnpg-loadbalancer.cloudnativepg.svc.cluster.local -f /tmp/cnpg-backup.sql pg_dump: error: could not write to output file: No space left on device pg_dumpall: error: pg_dump failed on database "butler", exiting
=> (yagan) increase cnpg backup volume to 500Gi

fleet/lib/cnpg-cluster/overlays/yagan/cluster-cnpg-cluster.yaml
These changes were necessary due to persistent 100% CPU utilization on the primary node (cnpg-cluster-8).
Changes applied:
- Increase CPU from 16 to 48
Closes: https://rubinobs.atlassian.net/browse/IT-6219
=> (cp/yagan) Increase CPU from 16 to 48

fleet/lib/cnpg-cluster/overlays/pillan/cluster-cnpg-cluster.yaml
bumping `postgres` version on the `TTS` to `16.8`
=> (fleet/cnpg-cluster) bump cnpgsphere 16.8 on pillan

fleet/lib/ccs-grafana/fleet.yaml, fleet/lib/ccs-influxdb/fleet.yaml, fleet/lib/cert-manager-conf/fleet.yaml, fleet/lib/cnpg-cluster/fleet.yaml, fleet/lib/fleet-conf/overlays/ls/gitrepo-antu.yaml, fleet/lib/fleet-conf/overlays/ls/gitrepo-gaw.yaml, fleet/lib/fleet-conf/overlays/ls/gitrepo-konkong.yaml, fleet/lib/fleet-conf/overlays/ls/gitrepo-luan.yaml, fleet/lib/fleet-conf/overlays/ls/gitrepo-manke.yaml, fleet/lib/htcondor/fleet.yaml, fleet/lib/keycloak-pg/fleet.yaml, fleet/lib/keycloak/fleet.yaml, fleet/lib/kube-prometheus-stack/fleet.yaml, fleet/lib/metallb-conf/fleet.yaml, fleet/lib/metallb-demo/fleet.yaml, fleet/lib/mimir-pre/fleet.yaml, fleet/lib/multus-conf/fleet.yaml, fleet/lib/multus-demo/fleet.yaml, fleet/lib/rook-ceph-cluster/fleet.yaml, fleet/lib/rook-ceph-conf/fleet.yaml, fleet/lib/rook-ceph-demo/fleet.yaml
this PR changes the `clusterName` for fleet that got randomized on the last version into `clusterSelector` to match the name of the cluster, this affects all base clusters.
this PR hangs from https://github.com/lsst-it/k8s-cookbook/pull/943/
=> (fleet/bundles) change clustername to clusterSelector for LS

fleet/lib/rook-ceph-conf/charts/elqui/templates/cephobjectstore-lfa.yaml
- the user for the `LFA` has a BucketMaxSize of 2.5PiB so, just in case, we are setting the quota on the data pool to 3PiB.
=> (fleet/rook-ceph-conf) set 3PiB on lfa data pool on elqui.

fleet/lib/htcondor/overlays/yagan/deployment-htcondor-worker.yaml
- checking on the `initContainer` first if the link exist.
=> (fleet/htcondor) fix initcontainer summit worker

fleet/lib/loki/overlays/kueyen/values.yaml, fleet/lib/loki/values.yaml
- Remove Service as `LoadBalancer`, leaving `ClusterIP` as the default Service Type from the values.
- Update secret name as `tls-loki-ingress`.
Unblocks PR: #963
=> (kueyen) Remove service allowing use of default Ingress with Loki

fleet/lib/rook-ceph-conf/charts/konkong/templates/cephobjectstoreusers-1pass-rotate-keys.yaml, fleet/lib/rook-ceph-conf/charts/konkong/values.yaml
This is to support live rotation of s3 credentials.
=> (konkong) add 2nd s3 creds to rgw lsstcam user

fleet/lib/rook-ceph-conf/charts/pillan/values.yaml
Credentials have been copied from pillan rgw (or created from scratch) in the 1pass `oods.tu` vault for these users.
=> (pillan) add rgw calib, rubintv, & saluser users

fleet/lib/cnpg-cluster/overlays/yagan/cluster-cnpg-cluster.yaml
bumps the `postgres` version to `16.8`
=> (fleet/cnpg-cluster) bump cnpgsphere 16.8 on yagan

fleet/lib/cnpg-cluster/overlays/manke/cnpg-backup.yaml, fleet/lib/cnpg-cluster/overlays/pillan/cnpg-backup.yaml, fleet/lib/cnpg-cluster/overlays/ruka/cnpg-backup.yaml, fleet/lib/cnpg-cluster/overlays/yagan/cnpg-backup.yaml
bumps the `postgres` image on the backup `cronjob` to `postgres` `16.8`
=> (fleet/cnpg-cluster) bump backup image to pg16.8

fleet/lib/grafana-dashboards/dashboards/deliverator-summary.json
`s3nd` >= `1.9.0` adds a `s3nd_` prefix to all metrics and generally renames the existing metrics. E.g. `tcp_info_bytes_sent` becomes `s3nd_s3_tcp_info_bytes_sent_total`.  The queries in the `Deliverator Summary` dashboard are updated to work with the old and new metric names to provide for a smooth transition.
=>  (fleet/grafana-dashboards) add s3nd_s3_ prefix to deliverator metrics

fleet/lib/alloy/overlays/antu/values.yaml, fleet/lib/alloy/overlays/kona/values.yaml
- add udp port for openvpn logs with a reasonable effort to apply labels 
- add udp port for rsyslog  <- this is a quick win since all the hosts are already sending to collector.ls and collector.cp we just change the A record and we dont have to touch the servers.
=> (fleet/alloy) add vpn and rsyslog connectors

fleet/lib/nexus-pre/external-secret-nexus-pg-creds.yaml, fleet/lib/nexus/values.yaml
Adds necessary PG env variables on the Nexus instance running on Ruka. This is currently being tested on fleet Ruka and is working as expected.
=> (fleet/nexus) add nexus pg env variables dev

fleet/lib/rook-ceph-conf/charts/ayekan/templates/cephobjectstore-lfa.yaml, fleet/lib/rook-ceph-conf/charts/elqui/templates/cephobjectstore-lfa.yaml, fleet/lib/rook-ceph-conf/charts/konkong/templates/cephobjectstore-lfa.yaml, fleet/lib/rook-ceph-conf/charts/pillan/templates/cephobjectstore-lfa.yaml, fleet/lib/rook-ceph-conf/charts/ruka/templates/cephobjectstore-lfa.yaml
This will prevent the automatic creation of `default.rgw...` pools. E.g.
```
default.rgw.log         14   32    182 B        2   24 KiB      0    1.1 TiB
default.rgw.control     15   32      0 B        8      0 B      0    1.1 TiB
default.rgw.meta        16   32      0 B        0      0 B      0    1.1 TiB
```
=> (fleet/rook-ceph-conf) always set a default realm when using CephObjectRealm
