lsst-it/k8s-cookbook

antu/rke/cluster.yml, antu/rook-ceph/ceph-storageclass.yaml, antu/rook-ceph/cephblockpool.yaml, antu/rook-ceph/cephcluster.yaml, antu/rook-ceph/rook-1.3.1/common.yaml, antu/rook-ceph/rook-1.3.1/operator.yaml, antu/rook-ceph/rook-1.3.1/toolbox.yaml, antu/rook-ceph/rook-ceph-k8s-cleanup.sh, antu/rook-ceph/rook-ceph-node-cleanup.sh, antu/rook-ceph/rook-ceph.sh
It appears that the ceph mgr may need to be running on a node with active OSDs?
=> coral ceph cluster components onto osd nodes

antu/rke/cluster.yml
The node has been tested and is ready to be reintegrated to the cluster
=> add back antu06

pillan/cnpg/.gitignore, pillan/cnpg/README.md, pillan/cnpg/cnpg-loadbalancer.yaml, pillan/cnpg/cnpg-recovery.yaml, pillan/cnpg/cnpg-scheduledbackups.yaml, pillan/cnpg/cnpg.sh
This is the cloudnativePG deployment needed at TTS and tested on the ruka cluster first.
=> (pillan) Deployment for cloudnativePG

ruka/kyverno/kyverno.sh, ruka/kyverno/policies/disallow-host-namespaces.yaml, ruka/kyverno/policies/disallow-privileged-containers.yaml, ruka/kyverno/policies/disallow_cri_sock_mount.yaml, ruka/kyverno/policies/disallow_default_namespace.yaml, ruka/kyverno/policies/limit-hostpath-vols.yaml, ruka/kyverno/policies/limit_hostpath_type_pv.yaml, ruka/kyverno/policies/require_pod_requests_limits.yaml
All kyverno policies are in `audit` only mode.
=> (ruka) add kyverno 1.7.3

pillan/kyverno/kyverno.sh, pillan/kyverno/policies/disallow-host-namespaces.yaml, pillan/kyverno/policies/disallow-privileged-containers.yaml, pillan/kyverno/policies/disallow_cri_sock_mount.yaml, pillan/kyverno/policies/disallow_default_namespace.yaml, pillan/kyverno/policies/limit-hostpath-vols.yaml, pillan/kyverno/policies/limit_hostpath_type_pv.yaml, pillan/kyverno/policies/require_pod_requests_limits.yaml, ruka/kyverno/policies/require_pod_requests_limits.yaml
Policies are in 'audit' only mode.
=> (pillan) add kyverno 1.8.1

yagan/cnpg/README.md, yagan/cnpg/cnpg-backup.sh, yagan/cnpg/cnpg-loadbalancer.yaml, yagan/cnpg/cnpg.sh
This deployment has the latest fixes and updates we been developing and its been working steady on Pillan for weeks.
=> CloudnativePG Deployment on Summit

pillan/cnpg/cnpg.sh, ruka/cnpg/cnpg.sh, yagan/cnpg/cnpg.sh
this was tested on Ruka first and running.
Several postgresql parameters needed to be fine tuned: 
pinned version of postgres.
`imageName: ghcr.io/cloudnative-pg/postgresql:14.5`
pg_hba.conf
`postgresql:
parameters:
max_connections: "500"
shared_buffers: 256MB
idle_session_timeout: 4h`
=> cloudnativePG pg_settings update

pillan/cnpg/cnpg.sh, ruka/cnpg/cnpg.sh, yagan/cnpg/cnpg.sh
Reverts lsst-it/k8s-cookbook#121
=> Revert "cloudnativePG pg_settings update"

pillan/cnpg/cnpg.sh, ruka/cnpg/cnpg.sh, yagan/cnpg/cnpg.sh
Due to trying to fix branches issues i lost the changes made on the clusters, so I am recommiting the changes again.
=> (cnpg) config fix for Ruka, Pillan and Yagan

manke/rke/cluster.yml
rke cluster definition for manke. (made from yagan's definition)
=> (manke) rke cluster definition

manke/cert-manager/.gitignore, manke/cert-manager/README.md, manke/cert-manager/cert-manager.sh
This script deploys the cert-manager for manke cluster
=> (manke) add cert-manager script

manke/rook-ceph/ceph-storageclass.yaml, manke/rook-ceph/cephblockpool.yaml, manke/rook-ceph/nfs/cephfs-jhome.yaml, manke/rook-ceph/nfs/cephfs-lsstdata.yaml, manke/rook-ceph/nfs/cephfs-project.yaml, manke/rook-ceph/nfs/cephfs-scratch.yaml, manke/rook-ceph/rook-ceph-cluster-values.yaml, manke/rook-ceph/rook-ceph-values.yaml, manke/rook-ceph/rook-ceph.sh, manke/rook-ceph/s3/ingress.yaml, manke/rook-ceph/s3/object_store.yaml
Follow script will install rook-ceph v1.10.10, ceph v16.2.10 and cephcsi v3.7.2.
2 disks per node - replica 3 - mngr 2 - mon 3 and SSL false (ingress in HTTP).
nodes clean up script also included.
=> (manke) rook-ceph operator

ruka/rook-ceph/rook-ceph.sh
To pickup the operator webhook being disabled.
=> (ruka) bump rook to 1.10.10

konkong/cert-manager/.gitignore, konkong/cert-manager/README.md, konkong/cert-manager/cert-manager.sh, konkong/ingress/ingress-nginx.sh, konkong/metallb/demo/metallb-lhn-demo.yaml, konkong/metallb/ippool.yaml, konkong/metallb/metallb.sh, konkong/multus/.gitignore, konkong/multus/demo/multus-lhn-demo.yaml, konkong/multus/multus-nad-lhn.yaml, konkong/multus/multus.sh, konkong/rke/.gitignore, konkong/rke/cluster.yml
This adds the following to the cookbook for the Konkong cluster:
- rke
- metalLB (added lhn)
- nginx Ingress
- cert-manager
- multus on the bridge interface
=> Konkong k8s Cookbook Operators

konkong/rook-ceph/.gitignore, konkong/rook-ceph/README.md, konkong/rook-ceph/demo/bucket_policy.json, konkong/rook-ceph/demo/s3demo.sh, konkong/rook-ceph/rook-ceph-cluster-values.yaml, konkong/rook-ceph/rook-ceph-values.yaml, konkong/rook-ceph/rook-ceph.sh, konkong/rook-ceph/s3/ingress.yaml, konkong/rook-ceph/s3/object_store.yaml, konkong/rook-ceph/scripts/rook-ceph-node-cleanup.sh
This contains the configuration and the operator install for the s3 on konkong as part of the LFA for the BTS.
this was tested with the provided script and works.
=> (konkong) setup rook-ceph for s3

kueyen/cnpg-replica/.gitignore, kueyen/cnpg-replica/README.md, kueyen/cnpg-replica/cnpg-loadbalancer.yaml, kueyen/cnpg-replica/cnpg-replica.sh, ruka/cnpg/cnpg-replica-lb.yaml, ruka/cnpg/cnpg.sh
This adds the deployment for the replica cluster (kueyen) and the necessary adjustments in the master cluster for this to work (ruka) 
-  README.md is updates with the correct usage instructions. (yes, i took the time to update the instructions)
=> cloudnativePG replica deployment and testing.

chonchon/metallb/demo/metallb-lhn-demo.yaml, chonchon/metallb/ippool.yaml, chonchon/multus/.gitignore, chonchon/multus/demo/demo.sh, chonchon/multus/demo/multus-demo.yaml, chonchon/multus/multus-nad-lhn.yaml, chonchon/multus/multus.sh
This will config multus to work using the br1800 interface and allocate the segment for the LHN (139.229.180.63-70) services on metallb.
=> (chonchon) LHN Config Multus/Metallb Update.

pillan/rook-ceph/cephblockpool.yaml, pillan/rook-ceph/rook-ceph-cluster-values.yaml
quotas been reach for s3 and the replication pool, plus some config debt on dashboard.
=> Update rook-ceph config for TTS

namkueyen/cert-manager/.gitignore, namkueyen/cert-manager/README.md, namkueyen/cert-manager/cert-manager.sh, namkueyen/ingress/ingress-nginx.sh, namkueyen/metallb/ippool.yaml, namkueyen/metallb/metallb.sh, namkueyen/rook-ceph/.gitignore, namkueyen/rook-ceph/README.md, namkueyen/rook-ceph/ceph-storageclass.yaml, namkueyen/rook-ceph/cephblockpool.yaml, namkueyen/rook-ceph/rook-ceph-cluster-values.yaml, namkueyen/rook-ceph/rook-ceph-values.yaml, namkueyen/rook-ceph/rook-ceph.sh, namkueyen/rook-ceph/scripts/rook-ceph-node-cleanup.sh
First revision of namkueyen cluster configuration.
=> (namkueyen) k8s cluster configuration 

kueyen/metallb/ippool.yaml, kueyen/rke/cluster.yml, kueyen/rook-ceph/rook-ceph-cluster-values.yaml
We needed to move kueyen from production into dev.
=> (kueyen) move to dev

yagan/rook-ceph/nfs/cephfs-auxtel.yaml, yagan/rook-ceph/rook-ceph.sh
Intended to replace the auxtel-archiver.cp.lsst.org:/repo export.
=> (yagan) add auxtel nfs export

namkueyen/rke/cluster.yaml
I noticed that the RKE Folder was missing inside the Namkueyen repository. This pull request was created to incorporate the folder where it belongs.
=> (namkueyen) add rke folder

manke/rook-ceph/nfs/cephfs-comcam.yaml, manke/rook-ceph/rook-ceph.sh
While there isn't currently a "comcam" in the BTS, an nfs export for comcam is being added to stay consistent with TTS.
=> (manke) add nfs-comcam export

chonchon/rook-ceph/rook-ceph.sh, gaw/rook-ceph/rook-ceph.sh, konkong/rook-ceph/rook-ceph.sh, kueyen/rook-ceph/rook-ceph.sh, luan/rook-ceph/rook-ceph.sh, lukay/rook-ceph/rook-ceph.sh, manke/rook-ceph/rook-ceph.sh, namkueyen/rook-ceph/nfs/cephfs-auxtel.yaml, namkueyen/rook-ceph/nfs/cephfs-comcam.yaml, namkueyen/rook-ceph/nfs/cephfs-jhome.yaml, namkueyen/rook-ceph/nfs/cephfs-lsstdata.yaml, namkueyen/rook-ceph/nfs/cephfs-obsenv.yaml, namkueyen/rook-ceph/nfs/cephfs-project.yaml, namkueyen/rook-ceph/nfs/cephfs-scratch.yaml, namkueyen/rook-ceph/rook-ceph-cluster-values.yaml, namkueyen/rook-ceph/rook-ceph.sh, namkueyen/rook-ceph/s3/ingress.yaml, namkueyen/rook-ceph/s3/object_store.yaml, pillan/rook-ceph/rook-ceph.sh, ruka/rook-ceph/rook-ceph.sh, yagan/rook-ceph/rook-ceph.sh, yepun/rook-ceph/rook-ceph.sh
This will renormalize the rook-ceph.sh script across all clusters after the recent per cluster nfs improvements and is intended to prepare for upgrading ceph to 17.2.6.
=> (* rook clusters) improve rook-ceph.sh; ensure ceph orch is enabled; enable ceph device monitoring;

ayekan/cert-manager/.gitignore, ayekan/cert-manager/README.md, ayekan/cert-manager/cert-manager.sh, ayekan/ingress/ingress-nginx.sh, ayekan/metallb/ippool.yaml, ayekan/metallb/metallb.sh, ayekan/prometheus/prometheus.sh, ayekan/prometheus/values.yaml, ayekan/rke/.gitignore, ayekan/rke/Makefile, ayekan/rke/cluster.yml, ayekan/rook-ceph/.gitignore, ayekan/rook-ceph/ceph-storageclass.yaml, ayekan/rook-ceph/cephblockpool.yaml, ayekan/rook-ceph/rook-ceph-cluster-values.yaml, ayekan/rook-ceph/rook-ceph-values.yaml, ayekan/rook-ceph/rook-ceph.sh, ayekan/rook-ceph/scripts/rook-ceph-node-cleanup.sh
Adds our basic startup kit for k8s cluster deployment.
k8s 1.25.9
- MetalLB
- Cert-Manager
- Ingress-Nginx
- rke
- prometheus
- Rook-Ceph
=> Ayekan Observability Cluster CookBook Implementation

yepun/cnpg/README.md, yepun/cnpg/cnpg-backup.sh, yepun/cnpg/cnpg-lb.yaml, yepun/cnpg/cnpg.sh
Keycloak needed a database outside the pixel zone and Cristian asked to be in Yepun
=> (yepun) add cloudnativePG deployment

yagan/rook-ceph/cephblockpool.yaml
we hit replicapool quota, this is to increase it to 10T
=> (yagan) increase replicapool quota

manke/keycloak/README.md, manke/keycloak/keycloak.sh, pillan/keycloak/README.md, pillan/keycloak/cert-manager.sh, pillan/keycloak/keycloak.sh, yagan/keycloak/README.md, yagan/keycloak/keycloak.sh
This adds the deployment of Keyclock to the Cookbook.
TTS - Pillan (includes cert-manager Issuer)
BTS - Manke (Cluster-Issuer Signs OK)
CP - Yagan (Cluster-Issuer Signs OK)
=> IT-4889 Keycloak Deployment

ruka/htcondor/htcondor-central-manager-deployment.yaml, ruka/htcondor/htcondor-central-manager-service.yaml, ruka/htcondor/htcondor-schedd-deployment.yaml, ruka/htcondor/htcondor-worker-deployment.yaml, ruka/htcondor/htcondor.sh
- Images code was moved to a repo 'htcondor-images'
- docker images were moved to dockerhub
- Code was cleaned and install script was updated. (verified working)
=> (ruka) add htcondor deployment

ayekan/exporters/deploy-exporters.sh, ayekan/exporters/deploy-target-configmap.sh, ayekan/prometheus/values.yaml
Add the config that has the network prometheus targets and use the configmap to scrape SNMP and ICMP
=> (ayekan) network prometheus targets

luan/kuma/ingress-kuma.yaml, luan/kuma/setup.sh
Redeployed under LS site per @hstockeb  request.
=> (luan) Deploy Kuma monitoring in La Serena site

ayekan/exporters/deploy-exporters.sh, ayekan/exporters/kminion-deployment.yaml
Add the kminion exporter for Apache kafka servers to the monitoring exporter set.
=> (ayekan) add kminion exporter for kafka

ayekan/exporters/configmap-snmp-config-tmpl.yaml, ayekan/exporters/deploy-exporters.sh, ayekan/exporters/externalsecret-snmp-community.yaml, ayekan/exporters/snmp-exporter.yaml, ayekan/external-secrets/clustersecretstore-onepassword.yaml
=> (ayekan) convert exporters to use external-secrets

rancher.cp/rancher/rancher.sh, rancher.cp/rancher/values.yaml, rancher.dev/rancher/rancher.sh, rancher.dev/rancher/values.yaml, rancher.ls/rancher/rancher.sh, rancher.ls/rancher/values.yaml, rancher.tu/rancher/rancher.sh, rancher.tu/rancher/values.yaml
See https://ranchermanager.docs.rancher.com/reference-guides/rancher-security/security-advisories-and-cves
=> (rancher.*) bump rancher to 2.7.9

fleet/lib/blackbox-exporter/fleet.yaml, fleet/lib/blackbox-exporter/values.yaml, fleet/site/tu/cluster/pillan/blackbox-exporter
=> (pillan) add prometheus-blackbox-exporter

fleet/lib/snmp-exporter-pre/.helmignore, fleet/lib/snmp-exporter-pre/Chart.yaml, fleet/lib/snmp-exporter-pre/files/sd/snmp-network.json, fleet/lib/snmp-exporter-pre/files/sd/snmp-raritan-pdu.json, fleet/lib/snmp-exporter-pre/files/snmp.yml, fleet/lib/snmp-exporter-pre/fleet.yaml, fleet/lib/snmp-exporter-pre/templates/cm-sd.yaml, fleet/lib/snmp-exporter-pre/templates/cm-snmp-configmap-tmpl.yaml, fleet/lib/snmp-exporter-pre/templates/externalsecret-snmp-community.yaml, fleet/lib/snmp-exporter/fleet.yaml, fleet/lib/snmp-exporter/values.yaml, fleet/site/tu/cluster/pillan/snmp-exporter, fleet/site/tu/cluster/pillan/snmp-exporter-pre
Depends on https://github.com/lsst-it/k8s-cookbook/pull/281
Note that snmp-exporter-pre will require some modifications to work with multiple clusters. That work is planned to be PR'd separately.
=> (pillan) add prometheus-snmp-exporter

fleet/lib/external-secrets/fleet.yaml, fleet/lib/kyverno-conf/fleet.yaml, fleet/lib/kyverno-conf/servicemonitor-kyverno-metrics.yaml, fleet/lib/kyverno/fleet.yaml, fleet/lib/mimir/fleet.yaml, fleet/lib/mimir/overlays/pillan/values.yaml, fleet/lib/mimir/overlays/ruka/values.yaml, fleet/lib/rook-ceph-cluster/fleet.yaml, fleet/lib/rook-ceph/fleet.yaml, fleet/site/cp/cluster/chonchon/prometheus-operator-crds, fleet/site/cp/cluster/lukay/prometheus-operator-crds, fleet/site/cp/lib/prometheus-operator-crds/fleet.yaml, fleet/site/dev/cluster/ayekan/prometheus-operator-crds, fleet/site/dev/cluster/kueyen/prometheus-operator-crds, fleet/site/dev/cluster/namkueyen/prometheus-operator-crds, fleet/site/dev/cluster/ruka/prometheus-operator-crds, fleet/site/ls/cluster/gaw/prometheus-operator-crds, fleet/site/ls/cluster/konkong/prometheus-operator-crds, fleet/site/ls/cluster/luan/prometheus-operator-crds, fleet/site/ls/cluster/manke/prometheus-operator-crds
=> (fleet/*) migrate prometheus crds to prometheus-operator-crds

fleet/lib/kube-prometheus-stack/fleet.yaml, fleet/lib/kube-prometheus-stack/overlays/ruka/values.yaml, fleet/site/dev/cluster/ruka/kube-prometheus-stack-pre
=> (ruka) convert kube-prometheus-stack to aggregator install

fleet/lib/metallb-conf/overlays/manke/ipaddresspool-htcondor.yaml, fleet/lib/multus-conf/overlays/manke/net-attach-def-htcondor.yaml, manke/htcondor/externalsecret-htcondor-pool-password.yaml, manke/htcondor/htcondor-central-manager-deployment.yaml, manke/htcondor/htcondor-central-manager-service.yaml, manke/htcondor/htcondor-worker-deployment.yaml, manke/htcondor/htcondor.sh
Deployment for HTCondor on the BTS, externalSecrets was added.
=> (manke) add htcondor deployment

rancher.cp/rancher/rancher.sh, rancher.ls/rancher/rancher.sh, rancher.tu/rancher/rancher.sh
rancher.dev was already bumped to 2.8.3 in https://github.com/lsst-it/k8s-cookbook/pull/303
=> (rancher.*) bump rancher to 2.8.3

fleet/lib/cnpg-cluster/overlays/manke/cnpg-loadBalancer.yaml, fleet/lib/cnpg-cluster/overlays/pillan/cnpg-loadBalancer.yaml
=> (pillan,manke) do not enable svc nodeports

fleet/lib/rook-ceph-cluster/overlays/ayekan/values.yaml
As the max capacitiy is ~1.7TiB.
=> (ayekan) reduce replicapool quota to 1.5TiB

fleet/lib/rook-ceph-cluster/overlays/ayekan/values.yaml, fleet/lib/rook-ceph-cluster/overlays/gaw/values.yaml, fleet/lib/rook-ceph-cluster/overlays/kueyen/values.yaml, fleet/lib/rook-ceph-cluster/overlays/luan/values.yaml, fleet/lib/rook-ceph-cluster/overlays/lukay/values.yaml, fleet/lib/rook-ceph-cluster/overlays/manke/values.yaml, fleet/lib/rook-ceph-cluster/overlays/namkueyen/values.yaml, fleet/lib/rook-ceph-cluster/overlays/pillan/values.yaml, fleet/lib/rook-ceph-cluster/overlays/ruka/values.yaml, fleet/lib/rook-ceph-cluster/overlays/yagan/values.yaml, fleet/lib/rook-ceph-cluster/overlays/yepun/values.yaml
Note that this change will require manual deletion of the `rook-ceph-block` sc.
=> (fleet/rook-ceph-cluster) enable modern ceph rbd features + discard flag

fleet/lib/rook-ceph-cluster/overlays/konkong/values.yaml
Disk need to be added so we can deliver the s3 to Michael soon.
2 x 30TB disk plus
fixing the old disk to 'by-id'
=> (fleet/rook-ceph-cluster) add disks to konkong

fleet/lib/snmp-exporter-pre/files/sd/dev/snmp-network.json
See https://github.com/lsst-it/network/blob/main/auto_inventory/vars/auto_inventory.yml
=> (fleet/snmp-exporter-pre) update snmp IPs from ansible inventory

pillan/rke/cluster.yml, rancher.tu/rancher/values.yaml, rancher.tu/rke/cluster.yml
Related to https://github.com/lsst-it/lsst-control/pull/1141
=>  (tu/*) bump k8s to v1.27.12-rancher1-1

chango/rke/cluster.yml, gaw/rke/cluster.yml, konkong/rke/cluster.yml, luan/rke/cluster.yml, manke/rke/cluster.yml, rancher.ls/rancher/values.yaml, rancher.ls/rke/cluster.yml
Bump versions for LS k8s Clusters
=> (ls*) bump v1.27.12

fleet/lib/rook-ceph-cluster/overlays/konkong/values.yaml
fix value from int to string as requiered by ceph
=> (fleet/rook-ceph-cluster) fix konkong values

fleet/lib/rook-ceph-conf/charts/konkong/templates/cephobjectstore-latiss-butler.yaml, fleet/lib/rook-ceph-conf/charts/konkong/templates/cephobjectstore-latiss-raw.yaml, fleet/lib/rook-ceph-conf/charts/konkong/templates/cephobjectstore-lsstcam-butler.yaml, fleet/lib/rook-ceph-conf/charts/konkong/templates/cephobjectstore-lsstcam-raw.yaml
Four S3 Resources were requested for the BTS
-  rubinobs-raw-latiss (1 TB) - latiss-raw.ls.lsst.org
-  rubinobs-butler-latiss (1 TB) - latiss-butler.ls.lsst.org
-  rubinobs-raw-lsstcam (6 TB) - lsstcam-raw.ls.lsst.org
-  rubinobs-butler-lsstcam (34 TB) - lsstcam-butler.ls.lsst.org
=> (konkong) add latiss and lsstcam s3

chonchon/rke/cluster.yml, lukay/rke/cluster.yml, rancher.cp/rancher/values.yaml, rancher.cp/rke/cluster.yml, yagan/rke/cluster.yml, yepun/rke/cluster.yml
bump k8s version on all cp clusters to v1.27.12
=> (cp*) bump v1.27.12

fleet/lib/rook-ceph-conf/charts/chonchon/templates/cephnfs-obs-env.yaml, fleet/lib/rook-ceph-conf/charts/chonchon/templates/cephobjectstore-lfa.yaml, fleet/lib/rook-ceph-conf/charts/chonchon/templates/cephobjectstore-rubintv.yaml
The cluster has Insufficient cpu to schedule pods.
=> (chonchon) reduce cephnfs & cephobjectstore cpu requests

template/external-secrets/external-secrets.sh
If the exteranl-secrets ns doesn't already exist, create it.
=> (template/external-secrets) create external-secrets ns

ayekan/rke/cluster.yml, kueyen/rke/cluster.yml, namkueyen/rke/cluster.yaml, rancher.dev/rke/cluster.yml, ruka/rke/cluster.yml
=> (site/dev) bump rke to v1.28.9-rancher1-1

fleet/lib/rook-ceph-cluster/overlays/ruka/values.yaml
To reduce memory usable and perhaps improve osd latency
=> (ruka) change rook osdsPerDevice to 1

fleet/lib/mimir/values.yaml
Reverts lsst-it/k8s-cookbook#474
=> Revert "(fleet/mimir) change ingestor replication_factor to 2"

fleet/lib/mimir/values.yaml
Reverts lsst-it/k8s-cookbook#473
=> Revert "(fleet/mimir) disable zoneAwareReplication"

pillan/rke/cluster.yml, rancher.tu/rke/cluster.yml
Bump K8s to 1.28.9 on the TTS (rancher.tu/pillan)
=> (site/tu) bump rke to v1.28.9-rancher1-1

fleet/lib/kube-prometheus-stack/overlays/ruka/values.yaml, fleet/lib/snmp-exporter-pre/files/sd/dev/snmp-power.json
Also add icmp up/down monitoring for the ups/power devices.
=> (ruka) merge ups/power monitoring into snmp-power job

chonchon/rke/cluster.yml, lukay/rke/cluster.yml, rancher.cp/rke/cluster.yml, yagan/rke/cluster.yml, yepun/rke/cluster.yml
bumping k8s to infinity and beyond!!! but only to v1.28.9
=> (site/cp) bump rke to v1.28.9-rancher1-1

ayekan/rke/cluster.yml, kueyen/rke/cluster.yml, namkueyen/rke/cluster.yaml, rancher.dev/rke/cluster.yml, ruka/rke/cluster.yml
=> (site/dev) bump rke to v1.28.10-rancher1-1

pillan/rke/cluster.yml, rancher.tu/rke/cluster.yml
=> (site/tu) bump rke to v1.28.10-rancher1-1

gaw/rke/cluster.yml, konkong/rke/cluster.yml, luan/rke/cluster.yml, manke/rke/cluster.yml, rancher.ls/rke/cluster.yml
=> (site/ls) bump rke to v1.28.10-rancher1-1

antu/rke/cluster.yml
sorry, forgot Antu since it is kinda new.
=> (antu) bump k8s to v1.28.10

chonchon/rke/cluster.yml, fleet/lib/rook-ceph-cluster/overlays/chonchon/values.yaml
- Add Chonchon04 and 05
- Add disk into Ceph
=> (cluster/chonchon) add nodes and disk

fleet/lib/rook-ceph-cluster/overlays/ruka/values.yaml, ruka/rke/cluster.yml
ruka was replaced, and now it is not using rke1 but this needs to be merged to close the loop.
=> (ruka) replace ruka01

ayekan/rke/cluster.yml, kueyen/rke/cluster.yml, namkueyen/rke/cluster.yaml, rancher.ls/rke/cluster.yml, ruka/rke/cluster.yml
moving del site to k8s v1.28.12-rancher1-1
=> (site/dev) bump rke to v1.28.12-rancher1-1

fleet/lib/htcondor/overlays/manke/deployment-htcondor-worker.yaml, fleet/lib/htcondor/overlays/ruka/deployment-htcondor-worker.yaml, fleet/lib/htcondor/overlays/yagan/deployment-htcondor-worker.yaml
move /rsphome into /home as requested.
=> (role/htcondor) move NFS from rsphome to home

pillan/rke/cluster.yml, rancher.tu/rke/cluster.yml
bump k8s version to `1.28.12` on TU
=> (site/tu) bump rke to v1.28.12-rancher1-1

antu/rke/cluster.yml, gaw/rke/cluster.yml, konkong/rke/cluster.yml, luan/rke/cluster.yml, manke/rke/cluster.yml, rancher.dev/rke/cluster.yml
bumping k8s version to 1.28.12 👍🏻
=> (site/ls) bump rke to v1.28.12-rancher1-1

chonchon/rke/cluster.yml, lukay/rke/cluster.yml, rancher.cp/rke/cluster.yml, yagan/rke/cluster.yml, yepun/rke/cluster.yml
=> (site/cp) bump rke to v1.28.12-rancher1-1

fleet/lib/ccs-grafana/base/dashboard-ccs-database.yaml, fleet/lib/ccs-grafana/base/dashboard-ccs-tasks.yaml, fleet/lib/ccs-grafana/base/dashboard-ccs-traffic.yaml, fleet/lib/ccs-grafana/base/dashboard-kafka-proxy.yaml, fleet/lib/ccs-grafana/base/kustomization.yaml, fleet/lib/ccs-grafana/values.yaml, fleet/lib/ccs-influxdb/base/externalsecret-influxdb.yaml, fleet/lib/ccs-influxdb/values.yaml, fleet/s/cp/c/yagan/ccs-grafana, fleet/s/cp/c/yagan/ccs-influxdb, fleet/s/ls/c/manke/ccs-grafana, fleet/s/ls/c/manke/ccs-influxdb, fleet/s/tu/c/pillan/ccs-grafana, fleet/s/tu/c/pillan/ccs-influxdb
This was tested on Kueyen, and it is working OK. This deployment will monitor the cameras in each site.
I already created the secrets on 1password.
=> (ccs-grafana/ccs-influxdb) deploy on pillan, manke & yagan

fleet/lib/fleet-conf/overlays/cp/gitrepo-chonchon.yaml, fleet/lib/fleet-conf/overlays/cp/gitrepo-lukay.yaml, fleet/lib/fleet-conf/overlays/cp/gitrepo-rancher.yaml, fleet/lib/fleet-conf/overlays/cp/gitrepo-yagan.yaml, fleet/lib/fleet-conf/overlays/cp/gitrepo-yepun.yaml, fleet/lib/fleet-conf/overlays/dev/gitrepo-rancher.yaml, fleet/lib/fleet-conf/overlays/dev/gitrepo-ruka.yaml, fleet/lib/fleet-conf/overlays/ls/gitrepo-antu.yaml, fleet/lib/fleet-conf/overlays/ls/gitrepo-gaw.yaml, fleet/lib/fleet-conf/overlays/ls/gitrepo-konkong.yaml, fleet/lib/fleet-conf/overlays/ls/gitrepo-luan.yaml, fleet/lib/fleet-conf/overlays/ls/gitrepo-manke.yaml, fleet/lib/fleet-conf/overlays/ls/gitrepo-rancher.yaml, fleet/lib/fleet-conf/overlays/tu/gitrepo-pillan.yaml, fleet/lib/fleet-conf/overlays/tu/gitrepo-rancher.yaml
This leaves correctDrift disabled on these dev clusters:
- ayekan
- kueyen
- namkueyen
=> (*) enable fleet correctDrift for all production clusters

ayekan/rke/cluster.yml, kueyen/rke/cluster.yml, namkueyen/rke/cluster.yaml, rancher.dev/rke/cluster.yml
update Dev RKE clusters to k8s `v1.29.8`
=> (site/dev) bump rke to v1.29.8-rancher1-1

fleet/lib/cnpg-cluster/overlays/yagan/cluster-cnpg-cluster.yaml, fleet/lib/cnpg-cluster/overlays/yagan/cnpg-backup.yaml
Last Night the Butler again ate the database space out, so now we double it! 🦾
=> (fleet/cnpg-cluster) PVC bump to 30Gi on yagan

fleet/lib/htcondor/overlays/yagan/deployment-htcondor-worker.yaml
well, here we are again, more NFS condor changes... more noodles. 🍜
=> (yagan/htcondor) fix NFS mounts to /data/lsstdata

fleet/lib/htcondor/overlays/yagan/deployment-htcondor-worker.yaml
I made a mistake in the path of the mount... `/data/lsstdata/base/auxtel/base/auxtel/oods` to `/data/lsstdata/base/auxtel/oods` 😢
=> (yagan/htcondor) fix error in NFS mounts

fleet/lib/external-secrets-conf/fleet.yaml, fleet/lib/rook-ceph-conf/charts/ruka/templates/cephobjectstoreuser-loki.yaml
Fix clustersecretstore for user Loki
=> (ruka) change loki user on the clustersecretstore

fleet/lib/rook-ceph-cluster/values.yaml
=> (fleet/rook-ceph-cluster) fix CPU request osd

fleet/lib/strimzi-kafka-dashboards/files/grafana-dashboards/strimzi-kafka.json, fleet/lib/strimzi-kafka-dashboards/files/grafana-dashboards/strimzi-kraft.json
Michael needed some fix on this dashboards for the strimzi Kafka.
=> (kafka/dashboards) fix Kraft and Kafka Dashboards

fleet/lib/rook-ceph-conf/charts/elqui/templates/cm-cephcli.yaml
The rook orch module breaks NFS configuration.
=> (elqui) permanently disable ceph orch

fleet/lib/rook-ceph-conf/charts/elqui/templates/cephobjectstore-lfa.yaml
Quotas will be set on buckets.
=> (elqui) rm lfa rgw pool quota

fleet/lib/keycloak/fleet.yaml
Reverts lsst-it/k8s-cookbook#705
=> Revert "Update Helm release keycloak to v24.2.2"

fleet/lib/grafana-dashboards/dashboards/PDUs.json
add summit and base pdu dashboard
=> (antu) add pdu dashboard

fleet/lib/rook-ceph-conf/charts/elqui/templates/cephobjectstore-lfa.yaml, fleet/lib/rook-ceph-conf/charts/elqui/templates/cephobjectstoreuser-calib.yaml, rke2/elqui/rook-ceph/s3/README.md, rke2/elqui/rook-ceph/s3/rubinobs-butler-lifecycle.json, rke2/elqui/rook-ceph/s3/users-rubinobs-butler-comcam-policy.json, rke2/elqui/rook-ceph/s3/users-rubinobs-butler-latiss-policy.json, rke2/elqui/rook-ceph/s3/users-rubinobs-butler-lsstcam-policy.json, rke2/elqui/rook-ceph/s3/users-rubinobs-calibrations-policy.json, rke2/elqui/rook-ceph/s3/users-rubinobs-raw-comcam-policy.json, rke2/elqui/rook-ceph/s3/users-rubinobs-raw-latiss-policy.json, rke2/elqui/rook-ceph/s3/users-rubinobs-raw-lsstcam-policy.json
this contains the `users`, `bucket creation`, `quotas`, `policies` and `life-cycles` for all the `s3-butler` storage in the summit.
=> S3 Butler for Summit

fleet/lib/rook-ceph-conf/charts/luan/templates/cephnfs-backup.yaml, fleet/lib/rook-ceph-conf/charts/luan/templates/cm-cephcli.yaml
we need to backup most of the NFS on the BTS and we currently only have space in `Luan`
=> (fleet/rook-ceph-conf) add backup nfs for luan

rke2/elqui/rook-ceph/s3/README.md
fixed some typos, changed the entry-point and tested every command to know it works correctly.
=> (rke2/elqui) fix README.md rook-ceph

fleet/lib/grafana-dashboards/dashboards/kubernetes-api-server.json
=> (obs/kubernetes) fix datasource

fleet/lib/grafana-dashboards/dashboards/DIsk IO Manke.json, fleet/lib/grafana-dashboards/dashboards/DIsk IO Yagan.json, fleet/lib/grafana-dashboards/dashboards/HTTP Prober.json, fleet/lib/grafana-dashboards/dashboards/Node Exporter.json, fleet/lib/grafana-dashboards/dashboards/Strimzi Kafka Broker Latency.json, fleet/lib/grafana-dashboards/dashboards/Strimzi Kafka Broker Throttling.json, fleet/lib/grafana-dashboards/dashboards/kubernetes-compute-resources-namespace-workloads.json, fleet/lib/grafana-dashboards/dashboards/kubernetes-compute-resources-pod.json, fleet/lib/grafana-dashboards/dashboards/kubernetes-kubelet.json, fleet/lib/grafana-dashboards/dashboards/kubernetes-networking-cluster.json, fleet/lib/grafana-dashboards/dashboards/kubernetes-networking-namespace-pod.json, fleet/lib/grafana-dashboards/dashboards/kubernetes-persistent-volumes.json
this fixes and add some new dashboards to the grafana deployment
=> (fleet/dashboards) update dashboards

fleet/lib/grafana-dashboards/dashboards/grafenomenal-metricwacth-3000.json, fleet/lib/grafana-dashboards/dashboards/kubernetes-overview.json, fleet/lib/grafana-dashboards/dashboards/pdu-overview.json, fleet/lib/grafana-dashboards/dashboards/power-overview.json
add grafenomenal, kubernetes, pdu and power overview
delete old pdu dashboard.
=> (fleet/grafana-dashboards) add new overview dashboards

fleet/lib/kube-prometheus-stack/overlays/antu/values.yaml, fleet/lib/snmp-exporter-pre/files/sd/ls/snmp-network.json
increases scrape timeout for network devices
update network device list and sort alphabetically.
=> (kube-prometheus-stack/antu) fix network scraping

fleet/lib/kube-prometheus-stack/overlays/antu/values.yaml
pdu timeout and scrape interval reduced
network timeout reduced and scrape increased.
=> (antu) adjust timeout and scrape interval

fleet/lib/snmp-exporter-pre/files/sd/ls/snmp-raritan-pdu.json
- updated wrong fqdn
- removed repeated ip addresses
=> (fleet/snmp-exporter) update pdu fqdn

fleet/lib/nexus/fleet.yaml
Add missing parameter to address certificate issues on CP Instance of Yepun.
=> (nexus) add secreName to ingress Yepun

fleet/lib/rook-ceph-cluster/fleet.yaml, fleet/lib/rook-ceph/fleet.yaml, fleet/lib/rook-ceph/values.yaml
Reverts lsst-it/k8s-cookbook#862
=> Revert "(fleet/rook-ceph) bump rook-ceph to v17.0.0"

fleet/lib/rook-ceph-cluster/overlays/yagan/values.yaml
The disk died, we cut the power for a few mins didn't come back. (@badenerb  found another exact disk 👏🏻 )
=> (fleet/rook-ceph-cluster) replace yagan01 disk

fleet/lib/cnpg-cluster/overlays/yagan/cluster-cnpg-cluster.yaml
Bump - `CPU -> 16` | `MEM -> 64Gi`
=> (fleet/cnpg-cluster) bump cnpg resource yagan

fleet/lib/cnpg-cluster/overlays/yagan/cluster-cnpg-cluster.yaml
- again something is growing beyond what they told us.
=> (fleet/cnpg-cluster) bump pvc yagan 150Gi

fleet/lib/openvpn-db/fleet.yaml
Increase timeout to allow it to complete resource creation.
=> (openvpn) increase timeout counter

fleet/lib/rook-ceph-cluster/overlays/konkong/values.yaml
- Add cephBlockPool for the rook-ceph-block storageClass.
*when this gets merged, continue here* https://github.com/lsst-it/k8s-cookbook/pull/906
=> (fleet/rook-ceph-cluster) add cephBlockPool to KonKong

fleet/lib/rook-ceph-conf/charts/ayekan/templates/obc-rubinobs-raw-comcam-test.yaml, fleet/lib/rook-ceph-conf/charts/ayekan/templates/obc-rubinobs-raw-latiss-test.yaml, fleet/lib/rook-ceph-conf/charts/ayekan/templates/obc-rubinobs-raw-lsstcam-test.yaml, fleet/lib/rook-ceph-conf/charts/elqui/templates/obc-rubinobs-raw-comcam-test.yaml, fleet/lib/rook-ceph-conf/charts/elqui/templates/obc-rubinobs-raw-latiss-test.yaml, fleet/lib/rook-ceph-conf/charts/elqui/templates/obc-rubinobs-raw-lsstcam-test.yaml, fleet/lib/rook-ceph-conf/charts/konkong/templates/obc-rubinobs-raw-latiss-test.yaml, fleet/lib/rook-ceph-conf/charts/konkong/templates/obc-rubinobs-raw-lsstcam-test.yaml, fleet/lib/rook-ceph-conf/charts/pillan/templates/obc-rubinobs-raw-comcam-test.yaml, fleet/lib/rook-ceph-conf/charts/pillan/templates/obc-rubinobs-raw-latiss-test.yaml, fleet/lib/rook-ceph-conf/charts/ruka/templates/obc-rubinobs-raw-comcam-test.yaml, fleet/lib/rook-ceph-conf/charts/ruka/templates/obc-rubinobs-raw-latiss-test.yaml, fleet/lib/rook-ceph-conf/charts/ruka/templates/obc-rubinobs-raw-lsstcam-test.yaml
Related to https://github.com/lsst-it/lsst-control/pull/1763
=>  (pillan,konkong,elqui) add rubinobs-raw-{latiss,comcam,lsstcam}-test buckets

antu/rke/cluster.yml, rancher.ls/rke/cluster.yml
This PR goes well with: https://github.com/lsst-it/lsst-control/pull/1769
=> (site/ls) bump rke to v1.31.8-rancher1-1

fleet/lib/cnpg-cluster/overlays/ruka/cluster-cnpg-cluster.yaml
=> (fleet/cnpg-cluster) bump cnpgsphere 16.8 on ruka

rke2/rancher.ls/metallb/ipaddresspool-ingress.yaml, template/metallb/metallb.sh
- fixes weird issue not finding the version on the repo.
- changes the ingress to the same network as the hosts.
=> (template/metallb) fix script and ipaddresspool on rancher.ls

fleet/lib/metallb-conf/overlays/rancher.ls/ipaddresspool-ingress.yaml
- forgot to change it here as well.
=> (fleet/rancher.ls) change ip for ingress

fleet/lib/kube-prometheus-stack/overlays/antu/values.yaml, fleet/lib/prometheus-alerts/README.md, fleet/lib/prometheus-alerts/rules/prometheusrule-k8s.yaml, fleet/lib/prometheus-alerts/rules/prometheusrule-net.yaml
- add pvc alert for 20% remaining space
- change repeat interval to 1 year
- modify readme to current status
- remove emoji from hostdown
=> (fleet/prometheus-alerts) add pvc alert

fleet/lib/grafana-dashboards/dashboards/grafenomenal-metricwacth-3000.json, fleet/lib/grafana-dashboards/dashboards/kubernetes-compute-resources-node-pods.json, fleet/lib/grafana-dashboards/dashboards/kubernetes-compute-resources-throttling.json, fleet/lib/grafana-dashboards/dashboards/network-node-port.json, fleet/lib/grafana-dashboards/dashboards/network-node.json, fleet/lib/grafana-dashboards/dashboards/node-details.json, fleet/lib/grafana-dashboards/dashboards/postgresql-overview.json, fleet/lib/grafana-dashboards/dashboards/power-overview.json
- add new dashboards
- delete unnecesary dashbaords
- modify grafenomenal and k8s dashboards.
=> (fleet/grafana-dashboards) add new dashboards

lukay/rke/cluster.yml, yepun/rke/cluster.yml
This PR goes well with: https://github.com/lsst-it/lsst-control/pull/1779
=> (site/cp) bump rke to v1.31.8-rancher1-1

fleet/lib/rook-ceph-conf/charts/elqui/templates/cephobjectstoreusers-1pass-rotate-keys.yaml, fleet/lib/rook-ceph-conf/charts/elqui/values.yaml
To start rotation of the s3 creds.
=> (elqui) add 2nd s3 creds to rgw lsstcam user

rke2/ayekan/exporters/snmp-generator/README.md, rke2/ayekan/exporters/snmp-generator/generator.yml, rke2/ayekan/exporters/snmp-generator/mibs/BEGEMOT-MIB.mib, rke2/ayekan/exporters/snmp-generator/mibs/BEGEMOT-PF-MIB.mib, rke2/ayekan/exporters/snmp-generator/mibs/FOKUS-MIB.mib, rke2/ayekan/exporters/snmp-generator/snmp.yml
added module for pfsense, mibs and readme file updated
=> (rke2/ayekan) add pfsense exporter module and mibs

fleet/lib/mimir-pre/externalsecret-mimir-s3.yaml
mimir missed the external secret api version update
=> (fleet/mimir-pre) fix external secret api

fleet/lib/mimir/values.yaml
Per: https://grafana.com/docs/mimir/latest/manage/run-production-environment/planning-capacity/
=> (fleet/mimir) tune resource limits

lukay/rke/cluster.yml, yepun/rke/cluster.yml
This PR goes well with: https://github.com/lsst-it/lsst-control/pull/1871
=> (site/cp) bump rke to v1.31.9-rancher1-1

fleet/lib/grafana-dashboards/dashboards/network-node.json, fleet/lib/snmp-exporter-pre/files/sd/ls/snmp-network.json
add main8-as02
modify network dashboard
=> (fleet/snmp-exporter-pre) add main8-as02

fleet/lib/rook-ceph-conf/charts/pillan/templates/cephobjectstore-lfa.yaml
=> (fleet/rook-ceph-conf) fix typo url pillan lfa
